### ISSUE TITLE
Every start of Yoshimi copies zyn sound banks to ~/.local/share/yoshimi/found/zynaddsubfx

### ISSUE THREAD

**Issue by suedwestlicht** [Yoshimi/yoshimi#103]
To minimize write operations it would be nice if this could be stopped.

**Comment by abrolag** [comment]
That's a bug :( It's only supposed to do it once!

I'll get on to it as soon as possible.

**Comment by abrolag** [comment]
Oops - didn't mean to close it.

**Comment by abrolag** [comment]
Fixed in the latest commit.

**Comment by suedwestlicht** [comment]
Confirmed.
Thank you.
