### ISSUE TITLE
Is there VST version of Yoshimi? 

### ISSUE THREAD

**Issue by Catsvilles** [Yoshimi/yoshimi#104]
Hi, I searched whole internet for this, so I suppose there is no such thing, but just in case, I'm asking here if there is maybe VST version of Yoshimi, preferably for Linux?

**Comment by kramlie** [comment]
No, but you can host it indirectly by using [Carla](https://github.com/falkTX/Carla) as a VST plugin, and then load the Yoshimi LV2 plugin from within it. That's what I do in my setup.

**Comment by Catsvilles** [comment]
@kramlie Thanks! This sound like the best solution for now.
