### ISSUE TITLE
Build system too strict? 

### ISSUE THREAD

**Issue by suedwestlicht** [Yoshimi/yoshimi#112]
```
[  9%] Generating ConsoleUI.cpp
/home/hm/src/yoshimi/2020-08-19/src/UI/ConsoleUI.fl:2: unknown version '1.0304'
[ 10%] Generating VectorUI.cpp
/home/hm/src/yoshimi/2020-08-19/src/UI/VectorUI.fl:2: unknown version '1.0304'
Scanning dependencies of target yoshimi
[ 11%] Building CXX object CMakeFiles/yoshimi.dir/Interface/InterChange.cpp.o
In file included from /home/hm/src/yoshimi/2020-08-19/src/Interface/InterChange.cpp:32:0:
/home/hm/src/yoshimi/2020-08-19/src/Misc/FileMgrFuncs.h: In function ‘std::__cxx11::string file::findFile(const string&, const string&, std::__cxx11::string)’:
/home/hm/src/yoshimi/2020-08-19/src/Misc/FileMgrFuncs.h:140:30: error: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Werror=unused-result]
     fscanf(fp,"%[^\n]", line);
                              ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
```

**Comment by abrolag** [comment]
Which build number are you trying to compile. That looks like the current master.
Non release versions will have most of the options set in CMakeLists. (line 37 onwards).
This is specifically to catch possible problems.
Having said that, it builds fine here, so is there anything about your setup that-s unusual?
Is that version number being shown referring to FLTK. If so we require version 1.3. This is mentioned in the Dependencies file.

**Comment by suedwestlicht** [comment]
I have fltk 1.3. 

Last version that built is

```
commit 2390758af7b96a244e7ee27977f56003e95663ef
Author: abrolag <willgodfrey@musically.me.uk>
Date:   Mon Aug 10 16:50:27 2020 +0100

    Provisional fix for SubSynth frequency bug
```

It throws the same warning but the warning doesn't prevent it from being built:

```
[  9%] Generating ConsoleUI.cpp
/home/hm/src/yoshimi/2020-08-11/src/UI/ConsoleUI.fl:2: unknown version '1.0304'
[ 10%] Generating VectorUI.cpp
/home/hm/src/yoshimi/2020-08-11/src/UI/VectorUI.fl:2: unknown version '1.0304'
Scanning dependencies of target yoshimi
[ 11%] Building CXX object CMakeFiles/yoshimi.dir/Interface/InterChange.cpp.o
In file included from /home/hm/src/yoshimi/2020-08-11/src/Interface/InterChange.cpp:32:0:
/home/hm/src/yoshimi/2020-08-11/src/Misc/FileMgrFuncs.h: In function ‘std::__cxx11::string file::findFile(const string&, const string&, std::__cxx11::string)’:
/home/hm/src/yoshimi/2020-08-11/src/Misc/FileMgrFuncs.h:140:30: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf(fp,"%[^\n]", line);
                              ^
[ 11%] Building CXX object CMakeFiles/yoshimi.dir/Interface/Data2Text.cpp.o
[ 12%] Building CXX object CMakeFiles/yoshimi.dir/Interface/MidiLearn.cpp.o
/home/hm/src/yoshimi/2020-08-11/src/Interface/MidiLearn.cpp:54:20: warning: ‘{anonymous}::textMsgBuffer’ defined but not used [-Wunused-variable]
     TextMsgBuffer& textMsgBuffer = TextMsgBuffer::instance();
                    ^
[ 12%] Building CXX object CMakeFiles/yoshimi.dir/Interface/MidiDecode.cpp.o
[ 13%] Building CXX object CMakeFiles/yoshimi.dir/Interface/RingBuffer.cpp.o
```

Diff of the CMakeLists.txt explains it:

```
hm@bubu:~/src/yoshimi/2020-08-19/src$ diff CMakeLists.txt ../../2020-08-11/src/CMakeLists.txt 
37c37
< add_definitions(-Werror) # warnings as errors
---
> #add_definitions(-Werror) # warnings as errors
44c44
< set (YOSHIMI_VERSION "1.7.2 M")
---
> set (YOSHIMI_VERSION "1.7.1 M")
```

I commented out "add_definitions(-Werror) # warnings as errors" and then it builds and works.

**Comment by abrolag** [comment]
On Thu, 20 Aug 2020 10:55:22 -0700
suedwestlicht <notifications@github.com> wrote:

>I have fltk 1.3. 
>
>Last version that built is
>
>```
>commit 2390758af7b96a244e7ee27977f56003e95663ef
>Author: abrolag <willgodfrey@musically.me.uk>
>Date:   Mon Aug 10 16:50:27 2020 +0100
>
>    Provisional fix for SubSynth frequency bug
>```
>
>It throws the same warning but the warning doesn't prevent it from being built:
>
>```
>[  9%] Generating ConsoleUI.cpp
>/home/hm/src/yoshimi/2020-08-11/src/UI/ConsoleUI.fl:2: unknown version '1.0304'
>[ 10%] Generating VectorUI.cpp
>/home/hm/src/yoshimi/2020-08-11/src/UI/VectorUI.fl:2: unknown version '1.0304'
>Scanning dependencies of target yoshimi
>[ 11%] Building CXX object CMakeFiles/yoshimi.dir/Interface/InterChange.cpp.o
>In file included from /home/hm/src/yoshimi/2020-08-11/src/Interface/InterChange.cpp:32:0:
>/home/hm/src/yoshimi/2020-08-11/src/Misc/FileMgrFuncs.h: In function ‘std::__cxx11::string file::findFile(const string&, const string&, std::__cxx11::string)’:
>/home/hm/src/yoshimi/2020-08-11/src/Misc/FileMgrFuncs.h:140:30: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
>     fscanf(fp,"%[^\n]", line);
>                              ^
>[ 11%] Building CXX object CMakeFiles/yoshimi.dir/Interface/Data2Text.cpp.o
>[ 12%] Building CXX object CMakeFiles/yoshimi.dir/Interface/MidiLearn.cpp.o
>/home/hm/src/yoshimi/2020-08-11/src/Interface/MidiLearn.cpp:54:20: warning: ‘{anonymous}::textMsgBuffer’ defined but not used [-Wunused-variable]
>     TextMsgBuffer& textMsgBuffer = TextMsgBuffer::instance();
>                    ^
>[ 12%] Building CXX object CMakeFiles/yoshimi.dir/Interface/MidiDecode.cpp.o
>[ 13%] Building CXX object CMakeFiles/yoshimi.dir/Interface/RingBuffer.cpp.o
>```
>
>Diff of the CMakeLists.txt explains it:
>
>```
>hm@bubu:~/src/yoshimi/2020-08-19/src$ diff CMakeLists.txt ../../2020-08-11/src/CMakeLists.txt 
>37c37
>< add_definitions(-Werror) # warnings as errors
>---
>> #add_definitions(-Werror) # warnings as errors  
>44c44
>< set (YOSHIMI_VERSION "1.7.2 M")
>---
>> set (YOSHIMI_VERSION "1.7.1 M")  
>```
>
>I commented out "add_definitions(-Werror) # warnings as errors" and then it builds and works.
>

But why have you set the version number back to V 1.7.1? That could cause some
confusion, and it will probably mean that it will pick up the wrong version of
the user guide.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by suedwestlicht** [comment]
These are the diffs from old to new, just the display of diff.

I didn't change the version in the new CMakeLists.txt. I commented out "add_definitions(-Werror)" only.
