### ISSUE TITLE
Renaming a voice does not change its name in patch data

### ISSUE THREAD

**Issue by y6nH** [Yoshimi/yoshimi#116]
Maybe I'm missing something here, so please correct me if there's something else I should be doing.

I'm running Yoshimi 1.7.2 on Manjaro 20.1.

When I create or modify a preset, save it in my personal preset bank, and then rename it, the new name shows up in the patch list window as it should. However, in the main window, it has the old name ("No Title", if created from scratch). Same in the edit windows, the mixer, and so on.

I inspected the files (in `/home/hugh/.local/share/yoshimi/found/yoshimi/banks/Bank of Hugh`), and the xiy/xiz files have the correct filenames, but in the XML data, the old name is still there.

**Comment by abrolag** [comment]
On Thu, 29 Oct 2020 13:46:03 -0700
Hugh <notifications@github.com> wrote:

>Maybe I'm missing something here, so please correct me if there's something else I should be doing.
>
>I'm running Yoshimi 1.7.2 on Manjaro 20.1.
>
>When I create or modify a preset, save it in my personal preset bank, and then rename it, the new name shows up in the patch list window as it should. However, in the main window, it has the old name ("No Title", if created from scratch). Same in the edit windows, the mixer, and so on.
>
>I inspected the files (in `/home/hugh/.local/share/yoshimi/found/yoshimi/banks/Bank of Hugh`), and the xiy/xiz files have the correct filenames, but in the XML data, the old name is still there.
>

This is a new take on a very old issue!

There two name fields. One is 'internal' embedded in the file itself, and the
other is the actual filename. The bank window is displaying the file name
(which you changed) and the other windows are showing the internal name (which
you didn't).

Had you changed the internal name (right click on the name field) before
saving, it would have been saved with that name, so both would match.

This becomes further complicated when someone saves an instrument externally,
then they, or someone else changes the filename. Without the internal name you
would have no idea what it actually was so could have two identical files
without realising it, or could load the wrong one without realising it if they
were different internally but had the same filename

Changing the internal name of an existing file would require loading it, making
the change, then resaving it, but if you already are running with all parts
filled, where would you load it to without losing one of the others?

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by y6nH** [comment]
I realised afterwards that I can right-click on the name field and re-save and it has the desired effect. So it works, but there are two UX issues here at the very least:

*  It feels a bit scary overwriting a saved patch – easy to make a mistake and overwrite the wrong one. It's not obvious on the patch list which one is loaded.
* It didn't occur to me to right-click on the patch name until I accidentally triggered the tooltip. This pretty basic function is well hidden.

Solutions, off the top of my head, may not be as easy as they seem:

* Highlight the last loaded patch in a different colour in the patch list. Put `*` by its name if it's been modified since load.
* Add the Name field to the Edit window, the one where you can set the Author and Comments metadata.

**Comment by abrolag** [comment]
Certainly since V 1.7.2 the most recent patch (if taken from a bank) is highlighted with a bold font.
I agree renaming the current instrument is not obvious, and I puzzled over this for some time.
Using the edit window is a pretty good idea, It would probably need the window to be made a little higher, but that won't be a problem.
I could also make the background of the name entry in the main window white. Hopefully that would give the hit it's editable.

I'll investigate, but I've only just released V 1.7.3, so unfortunately, this would miss it.

**Comment by y6nH** [comment]
I'm not seeing the bold font on a selected patch in 1.7.2.

**Comment by abrolag** [comment]
You need to enable it :)
New features are almost always off by default.
Yoshimi->Settings..->Switches->Enable Bank Highlight

**Comment by y6nH** [comment]
OK, that's an improvement. Thanks.
