### ISSUE TITLE
Add NSM support / update NSM patch

### ISSUE THREAD

**Issue by grammoboy2** [Yoshimi/yoshimi#120]
Hi,
There is a Non/New-session-manager (NSM) patch for Yoshimi, but it's never been applied. At the times when the patch was released, I could use Yoshimi in NSM, so the patch worked then. Would be nice if you could add NSM support to Yoshimi.  

http://non.tuxfamily.org/nsm/yoshimi-nsm.patch

**Comment by abrolag** [comment]
On Mon, 07 Dec 2020 02:23:09 -0800
grammoboy <notifications@github.com> wrote:

>Hi,
>There is a Non/New-session-manager (NSM) patch for Yoshimi, but it's never been applied. At the times when the patch was released, I could use Yoshimi in NSM, so the patch worked then. Would be nice if you could add NSM support to Yoshimi.  
>
>http://non.tuxfamily.org/nsm/yoshimi-nsm.patch
>
>

This is very old code and couldn't possibly be applied to current versions - it
makes reference to code that has considerably changed, and even some that simply
no longer exists. It also removes functionality that some people use :(

If anyone can find a non-destructive way to integrate NSM then we could
include it. However, none of the people currently working on Yoshimi have the
time or interest in it.

Sorry to be so negative, but it's a matter of practicality and priorities.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
