### ISSUE TITLE
Parameters Changed popup

### ISSUE THREAD

**Issue by iurienistor** [Yoshimi/yoshimi#123]
If I am opening Yoshimi plugin GUI, and than just close it, than this popup is shown saying that "Parameters Changed" even though I have not changed any synthesizer parameters. Probably the reason for this popup is for standalone version to notify the user to save the changes when the application is closed. For plugins/LV2 this notification is not necessary. For plugin if the synth/DSP parameters were changed than the host should be notified about this, and it will save the state when the host will be closed, or the user will press have Ctrl+S, and state of the plugin will be saved. If the user wants to closet the host and there are any unsaved plugin states the host will notify to save or will save automatically. Plugin GUIs during the session are open and closed many times, and showing this popup is not convenient.
![creenshot](https://user-images.githubusercontent.com/56111777/103075976-616fce80-45d5-11eb-97d1-027099c2fc99.png)

**Comment by abrolag** [comment]
Do you have 'Start With Default State' checked in 'Settings'->Switches? if so you need to uncheck it. This is probably badly worded, as it refers to a SAVED default state, not the startup one. Loading this at startup does make changes to the parameters so needs to be reported at some point.

**Comment by iurienistor** [comment]
Thank you. For me is unchecked. If I press save than this popup is no more showed.
