### ISSUE TITLE
lv2lint: binary exports superfluous globally visible symbols

### ISSUE THREAD

**Issue by dvzrv** [Yoshimi/yoshimi#125]
Hi! When building 1.7.4 for Arch Linux I also ran lv2lint against the built lv2 plugin. Although #110 fixes the crash that I was seeing then, I still have two fails reported by lv2lint:

```
'build/LV2_Plugin/yoshimi_lv2.so' -> 'src/LV2_Plugin/yoshimi_lv2.so'
lv2lint 0.8.0
Copyright (c) 2016-2020 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
<http://yoshimi.sourceforge.net/lv2_plugin>
/build/.local/share/yoshimi/presets
Basic configuration /build/.config/yoshimi/yoshimi.config not found, will use default settings
/build/.local/share/yoshimi/presets
Configuration /build/.config/yoshimi/yoshimi-0.instance not found, will use default settings
Starting in LV2 plugin mode
generating
Found 1 new banks in root /build/.local/share/yoshimi/found/yoshimi/banks

Found 1 instruments in 1 banks
Root 5. Bank set to 5 "newBank"
Missing recent history file
    [FAIL]  Plugin Symbols
              binary exports superfluous globally visible symbols:
                * _ZN8ConfigUI12cb_addpresetEP9Fl_ButtonPv
                * _ZN7PartUI_14showparametersEii
                * _ZN8FilterUI17cb_formant_q_dialEP11WidgetPDialPv
                * _ZN12ClearMenuBarC2Eiiii
                * _ZN13Panellistitem9send_dataEiifii
                * _ZN8OscilGen14basefunc_chirpEff
                * _ZN12PresetsStore18checkclipboardtypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
                * _ZN11SynthEngine8closeGuiEv
                * _ZN6ADnoteD2Ev
                * _ZN14EnvelopeParamsC1EhhP11SynthEngine
                * ... there is more, but the rest is being truncated
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
  <http://yoshimi.sourceforge.net/lv2_plugin#ExternalUI>
    [FAIL]  UI Symbols
              binary exports superfluous globally visible symbols:
                * _ZN8ConfigUI12cb_addpresetEP9Fl_ButtonPv
                * _ZN7PartUI_14showparametersEii
                * _ZN8FilterUI17cb_formant_q_dialEP11WidgetPDialPv
                * _ZN12ClearMenuBarC2Eiiii
                * _ZN13Panellistitem9send_dataEiifii
                * _ZN8OscilGen14basefunc_chirpEff
                * _ZN12PresetsStore18checkclipboardtypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
                * _ZN11SynthEngine8closeGuiEv
                * _ZN6ADnoteD2Ev
                * _ZN14EnvelopeParamsC1EhhP11SynthEngine
                * ... there is more, but the rest is being truncated
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
    [WARN]  UI Instance Access
              usage of instance-access is highly discouraged
              seeAlso: <http://lv2plug.in/ns/ext/instance-access>
    [WARN]  UI Mixed DSP/UI
              mixing DSP and UI code in same binary is discouraged
              seeAlso: <http://lv2plug.in/ns/extensions/ui#>
    [WARN]  UI Toolkit
              usage of unofficial external UI is discouraged
              seeAlso: <http://kxstudio.sf.net/ns/lv2ext/external-ui#Widget>
```

This is how I run lv2lint against the plugin, after build (before package creation):

```
  cp -v "build/LV2_Plugin/${pkgname}_lv2.so" "src/LV2_Plugin/"
  lv2lint -Mpack -I src/LV2_Plugin/ "http://yoshimi.sourceforge.net/lv2_plugin"
  rm -v "src/LV2_Plugin/${pkgname}_lv2.so"
```

**Comment by abrolag** [comment]
On Wed, 06 Jan 2021 08:18:10 -0800
David Runge <notifications@github.com> wrote:

>Hi! When building 1.7.4 for Arch Linux I also ran lv2lint against the built lv2 plugin. Although #110 fixes the crash that I was seeing then, I still have two fails reported by lv2lint:
>
>```
>'build/LV2_Plugin/yoshimi_lv2.so' -> 'src/LV2_Plugin/yoshimi_lv2.so'
>lv2lint 0.8.0
>Copyright (c) 2016-2020 Hanspeter Portner (dev@open-music-kontrollers.ch)
>Released under Artistic License 2.0 by Open Music Kontrollers
><http://yoshimi.sourceforge.net/lv2_plugin>
>/build/.local/share/yoshimi/presets
>Basic configuration /build/.config/yoshimi/yoshimi.config not found, will use default settings
>/build/.local/share/yoshimi/presets
>Configuration /build/.config/yoshimi/yoshimi-0.instance not found, will use default settings
>Starting in LV2 plugin mode
>generating
>Found 1 new banks in root /build/.local/share/yoshimi/found/yoshimi/banks
>
>Found 1 instruments in 1 banks
>Root 5. Bank set to 5 "newBank"
>Missing recent history file
>    [FAIL]  Plugin Symbols
>              binary exports superfluous globally visible symbols:
>                * _ZN8ConfigUI12cb_addpresetEP9Fl_ButtonPv
>                * _ZN7PartUI_14showparametersEii
>                * _ZN8FilterUI17cb_formant_q_dialEP11WidgetPDialPv
>                * _ZN12ClearMenuBarC2Eiiii
>                * _ZN13Panellistitem9send_dataEiifii
>                * _ZN8OscilGen14basefunc_chirpEff
>                * _ZN12PresetsStore18checkclipboardtypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
>                * _ZN11SynthEngine8closeGuiEv
>                * _ZN6ADnoteD2Ev
>                * _ZN14EnvelopeParamsC1EhhP11SynthEngine
>                * ... there is more, but the rest is being truncated
>              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
>  <http://yoshimi.sourceforge.net/lv2_plugin#ExternalUI>
>    [FAIL]  UI Symbols
>              binary exports superfluous globally visible symbols:
>                * _ZN8ConfigUI12cb_addpresetEP9Fl_ButtonPv
>                * _ZN7PartUI_14showparametersEii
>                * _ZN8FilterUI17cb_formant_q_dialEP11WidgetPDialPv
>                * _ZN12ClearMenuBarC2Eiiii
>                * _ZN13Panellistitem9send_dataEiifii
>                * _ZN8OscilGen14basefunc_chirpEff
>                * _ZN12PresetsStore18checkclipboardtypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
>                * _ZN11SynthEngine8closeGuiEv
>                * _ZN6ADnoteD2Ev
>                * _ZN14EnvelopeParamsC1EhhP11SynthEngine
>                * ... there is more, but the rest is being truncated
>              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
>    [WARN]  UI Instance Access
>              usage of instance-access is highly discouraged
>              seeAlso: <http://lv2plug.in/ns/ext/instance-access>
>    [WARN]  UI Mixed DSP/UI
>              mixing DSP and UI code in same binary is discouraged
>              seeAlso: <http://lv2plug.in/ns/extensions/ui#>
>    [WARN]  UI Toolkit
>              usage of unofficial external UI is discouraged
>              seeAlso: <http://kxstudio.sf.net/ns/lv2ext/external-ui#Widget>
>```
>
>This is how I run lv2lint against the plugin, after build (before package creation):
>
>```
>  cp -v "build/LV2_Plugin/${pkgname}_lv2.so" "src/LV2_Plugin/"
>  lv2lint -Mpack -I src/LV2_Plugin/ "http://yoshimi.sourceforge.net/lv2_plugin"
>  rm -v "src/LV2_Plugin/${pkgname}_lv2.so"
>```
>

Hi David.
I'm not seeing any of that here. However I couldn't duplicate your command
sequence so used the installed version with:

 /home/will/Downloads/lv2lint-0.8.0/x86_64-linux-gnu-buster/bin/lv2lint -Mpack
 -I /usr/local/lib/lv2/yoshimi.lv2/
 "http://yoshimi.sourceforge.net/lv2_plugin"^C
 will@devuan:~/yoshimi-code/build$ 


This just returned the previous ones:

Found 4926 instruments in 140 banks
Root 9. Bank set to 5 "Arpeggios"
    [FAIL]  Plugin Extension Data
              lv2:extensionData
<http://kxstudio.sf.net/ns/lv2ext/programs#Interface> not valid seeAlso:
<http://lv2plug.in/ns/lv2core#ExtensionData>
<http://yoshimi.sourceforge.net/lv2_plugin#ExternalUI> [WARN]  UI Instance
Access usage of instance-access is highly discouraged
              seeAlso: <http://lv2plug.in/ns/ext/instance-access>
    [WARN]  UI Mixed DSP/UI
              mixing DSP and UI code in same binary is discouraged
              seeAlso: <http://lv2plug.in/ns/extensions/ui#>
    [FAIL]  UI Toolkit
              UI toolkit <http://kxstudio.sf.net/ns/lv2ext/external-ui#Widget>
unkown seeAlso: <http://lv2plug.in/ns/extensions/ui#ui>

I'm afraid I still haven't worked out where I should point those URLs :(


-- 
Will J Godfrey
http://www.musically.me.uk
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
I've asked one of the other devs to take a look at this.

-- 
It wasn't me! (Well actually, it probably was)

... the hard part is not dodging what life throws at you,
but trying to catch the good bits.

**Comment by kramlie** [comment]
Does this fix the problem? https://github.com/Yoshimi/yoshimi/pull/127

**Comment by dvzrv** [comment]
@kramlie thanks, that fixed it indeed! :)
