### ISSUE TITLE
2.0: error: Failed to open library /usr/local/lib/lv2/yoshimi.lv2/yoshimi_lv2.so (/usr/local/lib/lv2/yoshimi.lv2/yoshimi_lv2.so: Undefined symbol "argp_parse")

### ISSUE THREAD

**Issue by yurivict** [Yoshimi/yoshimi#135]
This happens when I try to instantiate the LV2 plugin in ```jalv.qt5```.

OS: FreeBSD 12.2

**Comment by yurivict** [comment]
```LD_PRELOAD=/usr/local/lib/libargp.so``` helps.

**Comment by abrolag** [comment]
This is very strange. LV2 shouldn't be seeing argp at all!
Is it just with jalv, or do you get the same result with other hosts?
In any case, I've moved the config call further down the code (where it should have been), but I doubt it makes any difference.

**Comment by yurivict** [comment]
This is with all hosts.

**Comment by abrolag** [comment]
I'll see what I can find. Unfortunately we don't have anyone here these days with any experience of BSD so I'll be working blind :(

**Comment by kramlie** [comment]
When you run `cmake .`, do you hit [this message](https://github.com/Yoshimi/yoshimi/blob/master/src/CMakeLists.txt#L162).

**Comment by yurivict** [comment]
> When you run cmake ., do you hit this message?

Yes.

**Comment by abrolag** [comment]
On Thu, 08 Apr 2021 09:39:17 -0700
"yuri@FreeBSD" ***@***.***> wrote:

>> When you run cmake ., do you hit this message?  
>
>Yes.
>
Ah. I remember something about this now! Have you actually installed
argp-standalone? If not you need to do so.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by yurivict** [comment]
```argp-standalone``` is installed.
The problem is that the LV2 plugin gets linked with it when it shouldn't.

**Comment by kramlie** [comment]
While it's true that it is unnecessary to call argp inside the LV2 plugin, LV2 and the standalone binary share this code, and it is not easy to split this part with the current codebase. It's just too hard to change this without significant refactoring.

What about standalone Yoshimi, does it work without any `LD_PRELOAD` magic?

**Comment by yurivict** [comment]
> What about standalone Yoshimi, does it work without any LD_PRELOAD magic?

Yes.

**Comment by abrolag** [comment]
On Thu, 08 Apr 2021 23:34:03 -0700
"yuri@FreeBSD" ***@***.***> wrote:

>> What about standalone Yoshimi, does it work without any LD_PRELOAD magic?  
>
>Yes.
>
The latest commit to 'Master' has a small rationalisation in Config.cpp which
*might* make separating the apgp code a bit easier - not sure though.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Thu, 08 Apr 2021 23:34:03 -0700
"yuri@FreeBSD" ***@***.***> wrote:

>> What about standalone Yoshimi, does it work without any LD_PRELOAD magic?  
>
>Yes.
>
There is now a provisional fix for the whole problem in the current build.
It's a sledgehammer approach. I copied Config.cpp and Config.h across to the
LV2 code section, commented out all the argp bits and redirected the LV2
CMakeLists.txt file

It works correctly on Linux, but can you check in BSD in case there are bits I
missed.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Thu, 08 Apr 2021 23:34:03 -0700
"yuri@FreeBSD" ***@***.***> wrote:

>> What about standalone Yoshimi, does it work without any LD_PRELOAD magic?  
>
>Yes.
>

We'll try that again :(
For some reason it failed to include the Config files, but gave no
indication of the fact :(

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by yurivict** [comment]
The problem is gone in 2.0.1.

Thank you.
