### ISSUE TITLE
Typos in synth presets

### ISSUE THREAD

**Issue by jv84** [Yoshimi/yoshimi#137]
Is there some reason why synth presets are written as "syth" instead of synth?

**Comment by abrolag** [comment]
On Fri, 14 May 2021 16:20:32 -0700
jv84 ***@***.***> wrote:

>Is there some reason why synth presets are written as "syth" instead of synth?
>
It's purely historical. Paul originally named them like this in Zyn 2.2.1 and
later a variation of this was given to some, but still with syth. We found a
way to unify these. However, with so many people likely to have their own store
of presets we didn't want to make them completely unrecognisable, so it's still
there.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
