### ISSUE TITLE
Bug when modifying LFO frequency randomness via command line

### ISSUE THREAD

**Issue by CalumRaine** [Yoshimi/yoshimi#144]
The LFO "frequency randomness" parameter is set from the command line via "set fr".  However this doesn't seem to work because "set fr" is also the shortcut for "set frequency".  Therefore whenever I try to set randomness, it just switches to the frequency LFO instead.  I apologise if I'm wrong.

**Comment by abrolag** [comment]
On Sun, 04 Jul 2021 10:34:13 -0700
Calum Raine ***@***.***> wrote:

>The LFO "frequency randomness" parameter is set from the command line via "set fr".  However this doesn't seem to work because "set fr" is also the shortcut for "set frequency".  Therefore whenever I try to set randomness, it just switches to the frequency LFO instead.  I apologise if I'm wrong.
>

Yes, this is not good. However you can work round it by setting the category as
well so:

s am fr 30
s fr fr 60
s fi fr 90

The same works for reading them.
We will have to think about some alternative wording.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by CalumRaine** [comment]
Thank you, that solution works well.  Just one more thing, I seem to be able to set every LFO parameter from the command line except depth?  Is that correct?

**Comment by abrolag** [comment]
On Mon, 05 Jul 2021 03:07:02 -0700
Calum Raine ***@***.***> wrote:

>Thank you, that solution works well.  Just one more thing, I seem to be able to set every LFO parameter from the command line except depth?  Is that correct?
>
We use the term 'Intensity' to avoid a clash with 'Delay', although it
reports back as 'Depth' (just to make it interesting) :P

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by CalumRaine** [comment]
Brilliant, thanks.  I think the same issue exists when selecting waveforms in the oscillator: you cannot set "PULsesine" without just setting "PULse".  Anyway, this is a really impressive synthesiser, thanks for all your efforts.  Good day!

**Comment by abrolag** [comment]
On Mon, 05 Jul 2021 03:36:53 -0700
Calum Raine ***@***.***> wrote:

>Brilliant, thanks.  I think the same issue exists when selecting waveforms in the oscillator: you cannot set "PULsesine" without just setting "PULse".  Anyway, this is a really impressive synthesiser, thanks for all your efforts.  Good day!
>
Hi again :)
This is possible, in this case we made a mistake with the printed name. The
actual command is:
PSIne

I've also asked on the user list if we should in fact give this a different name
entirely as it's not very descriptive.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
In the current 'master' we've resolve the LFO using by using RR.
The falls in line with us using Rate instead of Frequency as it is now a Rate Randomness control.
