### ISSUE TITLE
find / -type f -name yoshimi_user_guide_version blocks loading Qtractor session

### ISSUE THREAD

**Issue by suedwestlicht** [Yoshimi/yoshimi#148]
With the recent yoshimi version I have problems when loading a Qtractor session with yoshimi as a LV2 plugin. It starts a process
`find / -type f -name yoshimi_user_guide_version`
which takes very long and sometimes blocks loading the qtractor session, sometimes it succeeds (when the file system is already in the OS' cache).

I think a plugin should never start such intense operations.

Edit:
The standalone version does the same.

**Comment by suedwestlicht** [comment]
I think running in the background doesn't help when a DAW (like Qtractor) catches stdout of the LV2 plugin. That might be an explanation why I couldn't load the session once.

Now the Qtractor session loads faster. But even after ending Qtractor the find process is still running.

I don't recommend running "find /" in an audio environment.

Yoshimi version 2.1.0 M

```
commit 604853457200396125c8512988dd973775023166
Author: abrolag <willgodfrey@musically.me.uk>
Date:   Mon Aug 23 20:02:42 2021 +0100

    Slight speed up for user guide search

```

**Comment by suedwestlicht** [comment]
It think the problem is in Interface/InterChange.cpp:

 ```
111     /*
 112      * We run this tiny low prio thread so that the manual
 113      * locations are already stored before anyone wants to
 114      * see it. This makes viewing it quicker.
 115      */
 116     static bool manseen = false;
 117     if (!manseen)
 118     {
 119         std::thread toCheck (manualCheck);
 120         toCheck.detach();
 121         manseen = true;
 122     }
```

Searching through all file systems (including network drives) although it's not sure if the manual will be read this day could be improved. I recommend installing the manual it in a fixed path (e.g. $PREFIX/share/doc/yoshimi) at install time and offer to search for it with a recommended search path "/usr/" (that can be altered by the user) when the user wants to view it and it's not found at the initial location.

**Comment by abrolag** [comment]
On Sat, 28 Aug 2021 00:52:45 -0700
suedwestlicht ***@***.***> wrote:

>I think running in the background doesn't help when a DAW (like Qtractor) catches stdout of the LV2 plugin. That might be an explanation why I couldn't load the session once.
>
>Now the Qtractor session loads faster. But even after ending Qtractor the find process is still running.
>
>I don't recommend running "find /" in an audio environment.
>
>Yoshimi version 2.1.0 M
>
>```
>commit 604853457200396125c8512988dd973775023166
>Author: abrolag ***@***.***>
>Date:   Mon Aug 23 20:02:42 2021 +0100
>
>    Slight speed up for user guide search
>
>```
>
OK.
Then I'll have to consider making Yoshimi look for the manual in specific
locations. I had wanted to avoid that to cover the problem where people
self-build but don't actually install Yoshimi so the only copy of the manual
could be anywhere in userland.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Sat, 28 Aug 2021 01:26:59 -0700
suedwestlicht ***@***.***> wrote:

>It think the problem is in Interface/InterChange.cpp:
>
> ```
>111     /*
> 112      * We run this tiny low prio thread so that the manual
> 113      * locations are already stored before anyone wants to
> 114      * see it. This makes viewing it quicker.
> 115      */
> 116     static bool manseen = false;
> 117     if (!manseen)
> 118     {
> 119         std::thread toCheck (manualCheck);
> 120         toCheck.detach();
> 121         manseen = true;
> 122     }
>```
>
>Searching through all file systems (including network drives) although it's not sure if the manual will be read this day could be improved. I recommend installing the manual it in a fixed path (e.g. $PREFIX/share/doc/yoshimi) at install time and offer to search for it with a recommended search path "/usr/" (that can be altered by the user) when the user wants to view it and it's not found at the initial location.
>

Please check the latest build.

I've reverted much of the code and initially tested specifically for:
/usr/share/doc/yoshimi/yoshimi_user_guide/files/yoshimi_user_guide_version

and:
/usr/local/share/doc/yoshimi/yoshimi_user_guide/files/yoshimi_user_guide_version

If both of those fail, I then use find in /home/

However a rather bigger problem is that modern browsers make a massive hit on
the processor at startup, which seems to be far more noticeable in LV2 than
when running standalone. If you are lucky, then running at 64 frames as I do,
you'll get 1 or 2 Xruns, but if you are unlucky you could get 800-900 :(

Trying to run in a different thread is actually no help unless there is a way
to force it to run on a different core, or maybe there is a way to pass the
details o to a completely separate process - although I thought popen was
supposed to do that.

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by suedwestlicht** [comment]
Yes, works for me.

Thanks, Will.
