### ISSUE TITLE
splashreference.svg is licensed as cc-by-nc

### ISSUE THREAD

**Issue by snd1** [Yoshimi/yoshimi#159]
https://github.com/Yoshimi/yoshimi/blame/master/Util/splashreference.svg#L719

This license is not compatible with the GPL2+ afaik, and not compatible with the DFSG from debian.

**Comment by abrolag** [comment]
This is a very old file (never used in releases AFAIK) it can be removed. The author is unknown so I don't consider I'm permitted to alter it. In the next commit it will be transferred to the Histories archive.
