### ISSUE TITLE
Pressing ESC Key: Same Effect As Alt+F4

### ISSUE THREAD

**Issue by GraysonPeddie** [Yoshimi/yoshimi#167]
While working in Yoshimi 2.2.0-1 in Arch Linux, I was working on an experimentation that was inspired by the "Castor" soundtrack from TRON Legacy (it's the scene where Sam Flynn had a chat with Zuse) and after I switch back to Yoshimi from MuSE Sequencer, I accidentally hit the ESC key and because I forgot to check which window has focus and I have lost everything I have done so far. Sure, I should have saved my changes frequently, but as the ESC key has the same effect as hitting Alt+F4, I just hit the ESC key accidentally.

Hitting ESC key in Firefox does nothing. Same for MuSE Sequencer and GNOME Terminal. I don't mind having an ESC key to close the window such as ADsynth or Effects panel, but I would like it if the ESC key could be disabled for the main window of Yoshimi. If I want to close Yoshimi, I can make use of Alt+F4 which takes more effort than hitting an ESC key. Plus, the use of Alt+F4 acts as a safeguard requiring two fingers to press the combinations.

**Comment by abrolag** [comment]
On Sat, 16 Jul 2022 08:57:59 -0700
Grayson Peddie ***@***.***> wrote:

>While working in Yoshimi 2.2.0-1 in Arch Linux, I was working on an experimentation that was inspired by the "Castor" soundtrack from TRON Legacy (it's the scene where Sam Flynn had a chat with Zuse) and after I switch back to Yoshimi from MuSE Sequencer, I accidentally hit the ESC key and because I forgot to check which window has focus and I have lost everything I have done so far. Sure, I should have saved my changes frequently, but as the ESC key has the same effect as hitting Alt+F4, I just hit the ESC key accidentally.
>
>Hitting ESC key in Firefox does nothing. Same for MuSE Sequencer and GNOME Terminal. I don't mind having an ESC key to close the window such as ADsynth or Effects panel, but I would like it if the ESC key could be disabled for the main window of Yoshimi. If I want to close Yoshimi, I can make use of Alt+F4 which takes more effort than hitting an ESC key. Plus, the use of Alt+F4 acts as a safeguard requiring two fingers to press the combinations.
>

Interesting. I don't think I've ever used the the escape key - at least, not
for many years.

This is an easy fix so will be in the next commit, specifically when the main
window has focus.

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Sat, 16 Jul 2022 08:57:59 -0700
Grayson Peddie ***@***.***> wrote:

><snip>
>
This is now fixed in the current master

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
This is now fixed in the current master


-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
