### ISSUE TITLE
problematic "options" in src/Misc/BuildScheduler.h

### ISSUE THREAD

**Issue by suedwestlicht** [Yoshimi/yoshimi#168]
To build yoshimi 06d176aa6cb45ef87232d22a3d93eb82ada36e2f on my oldish Ubuntu 16.04 I had to comment out
`#include <optional>`
on line 27 in src/Misc/BuildScheduler else I got
```
[  0%] Building CXX object CMakeFiles/yoshimi.dir/Interface/InterChange.cpp.o
In file included from /tmp/yoshimi/yoshimi/src/Params/PADnoteParameters.h:34:0,
                 from /tmp/yoshimi/yoshimi/src/Interface/InterChange.cpp:47:
/tmp/yoshimi/yoshimi/src/Misc/BuildScheduler.h:27:20: fatal error: optional: No such file or directory
compilation terminated.
```

Seems that commenting it out did no harm.

**Comment by abrolag** [comment]
On Mon, 15 Aug 2022 07:45:54 -0700
suedwestlicht ***@***.***> wrote:

>To build yoshimi 06d176aa6cb45ef87232d22a3d93eb82ada36e2f on my oldish Ubuntu 16.04 I had to comment out
>`#include <optional>`
>on line 27 in src/Misc/BuildScheduler else I got
>```
>[  0%] Building CXX object CMakeFiles/yoshimi.dir/Interface/InterChange.cpp.o
>In file included from /tmp/yoshimi/yoshimi/src/Params/PADnoteParameters.h:34:0,
>                 from /tmp/yoshimi/yoshimi/src/Interface/InterChange.cpp:47:
>/tmp/yoshimi/yoshimi/src/Misc/BuildScheduler.h:27:20: fatal error: optional: No such file or directory
>compilation terminated.
>```
>
>Seems that commenting it out did no harm.
>
Yes that's fine. It's inclusion relied on c++17, whereas we actually specify a
minimum of C++14. That's probably what your older distro has by default, and
there is fallback code for that.

I would add that if you can install a more recent version of GCC you will get a
slightly better build.

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
