### ISSUE TITLE
How to run with Ardour?

### ISSUE THREAD

**Issue by stefan-franz** [Yoshimi/yoshimi#171]
Hello, i installed Yoshimi as here described
https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/yoshimi_2.1.2.2~dfsg0-1_amd64.deb.html

Ardour 7.1 find the pluin. Single and multi version. 
But not able to load it. 

Can anyone help me?

**Comment by stefan-franz** [comment]
I made a new midi track in Ardour with Yoshimi, but the plugin was not loaded in the track as normal. 
workflow like here: https://www.youtube.com/watch?v=ytvqtsPxi7I
But it does not load in linux mint 21 - if it not works on linux mint 21 and Ardour, it's not the huge problem - i thought i ask maybe small things are the reason.

**Comment by abrolag** [comment]
On Tue, 15 Nov 2022 01:51:25 -0800
stefan-franz ***@***.***> wrote:

>I made a new midi track in Ardour with Yoshimi, but the plugin was not loaded in the track as normal. 
>workflow like here: https://www.youtube.com/watch?v=ytvqtsPxi7I
>But it does not load in linux mint 21 - if it not works on linux mint 21 and Ardour, it's not the huge problem - i thought i ask maybe small things are the reason. 
>
I'm a bit puzzled at how you got Ardour 7.1 (released quite recently) but
Yoshimi 2.1.2.2 (released nearly a year ago). It's likely they are using
different library versions which may account for the problem.

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
