### ISSUE TITLE
2.2.3: fatal error: 'bits/stdc++.h' file not found

### ISSUE THREAD

**Issue by yurivict** [Yoshimi/yoshimi#173]
```
/usr/ports/audio/yoshimi/work/yoshimi-2.2.3/src/Interface/Text2Data.cpp:24:9: fatal error: 'bits/stdc++.h' file not found
#include<bits/stdc++.h>
        ^~~~~~~~~~~~~~~
1 error generated.
```

Could you please provide a reference where is the header ```bits/stdc++.h``` documented?

Version: 2.2.3
clang-14
FreeBSD 13.1

**Comment by abrolag** [comment]
On Sun, 19 Feb 2023 08:51:02 -0800
***@***.***" ***@***.***> wrote:

>```
>/usr/ports/audio/yoshimi/work/yoshimi-2.2.3/src/Interface/Text2Data.cpp:24:9: fatal error: 'bits/stdc++.h' file not found
>#include<bits/stdc++.h>
>        ^~~~~~~~~~~~~~~
>1 error generated.
>```
>
>Could you please provide a reference where is the header ```bits/stdc++.h``` documented?
>
>
>Version: 2.2.3
>clang-14
>FreeBSD 13.1
>

Apologies! That's a non-standard GCC command we had for experimental purposes -
It should have been removed!

Someone also found a bug in the new CLI code for copy/paste so we'll posting a
bugfix release soon.

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
Corrected in current master
