### ISSUE TITLE
Build breaks when ALSA is enabled on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [Yoshimi/yoshimi#175]
FreeBSD also has functional ALSA libraries, but when ALSA is enabled in CMakeLists.txt the build then fails:

```
/usr/ports/audio/yoshimi/work/yoshimi-2.2.2.1/src/MusicIO/AlsaEngine.cpp:581:22: error: duplicate case value '-32'
                case -ESTRPIPE:
                     ^
/usr/ports/audio/yoshimi/work/yoshimi-2.2.2.1/src/MusicIO/AlsaEngine.cpp:577:22: note: previous case defined here
                case -EPIPE:
                     ^
/usr/ports/audio/yoshimi/work/yoshimi-2.2.2.1/src/MusicIO/AlsaEngine.cpp:612:14: error: duplicate case value '-32'
        case -EPIPE:
             ^
/usr/ports/audio/yoshimi/work/yoshimi-2.2.2.1/src/MusicIO/AlsaEngine.cpp:606:14: note: previous case defined here
        case -ESTRPIPE:
             ^
2 errors generated.
```

I am not sure where ```ESTRPIPE``` comes from.

Version: 2.2.2.1
clang-14
FreeBSD 13.1

**Comment by abrolag** [comment]
On Sun, 19 Feb 2023 10:40:47 -0800
***@***.***" ***@***.***> wrote:

>ESTRPIPE


That's plain weird. This is a constant defined in ALSA and is *not* 32.
https://pub.dev/documentation/dart_alsa/latest/alsa_generated_bindings/ESTRPIPE-constant.html

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by yurivict** [comment]
```
$ grep -r ESTRPIPE /usr/local/include/alsa/
/usr/local/include/alsa/pcm.h:#ifndef ESTRPIPE
/usr/local/include/alsa/pcm.h:#define ESTRPIPE EPIPE
```

**Comment by yurivict** [comment]
```
$ pkg which /usr/local/include/alsa/pcm.h
/usr/local/include/alsa/pcm.h was installed by package alsa-lib-1.2.2_1
```

**Comment by abrolag** [comment]
On Sun, 19 Feb 2023 11:41:13 -0800
***@***.***" ***@***.***> wrote:

>```
>$ grep -r ESTRPIPE /usr/local/include/alsa/
>/usr/local/include/alsa/pcm.h:#ifndef ESTRPIPE
>/usr/local/include/alsa/pcm.h:#define ESTRPIPE EPIPE
>```
>
That appears to be something changed when someone ported ALSA to BSD. It's
quite different on Linux as it permits different types of recovery and
associated messages.

I suppose you could just replace it with 86, but I've no idea what else might
have been changed/omitted.

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
Is this still a problem, or have you resolved it?

**Comment by yurivict** [comment]
No. The port still has this patch changing the default:
```
--- src/globals.h.orig  2023-02-19 18:22:47 UTC
+++ src/globals.h
@@ -126,8 +126,8 @@ typedef unsigned int  uint;
 #define DEFAULT_NAME "Simple Sound"
 #define UNTITLED "No Title"
 
-#define DEFAULT_AUDIO alsa_audio
-#define DEFAULT_MIDI alsa_midi
+#define DEFAULT_AUDIO jack_audio
+#define DEFAULT_MIDI jack_midi
  
 #define FORCED_EXIT 16
```

**Comment by yurivict** [comment]
cmake should look for Qt using a like like this:
```
find_package(Qt5 COMPONENTS Core Gui Svg Widgets REQUIRED)
```

It doesn't do this?

**Comment by abrolag** [comment]
On Tue, 02 May 2023 14:09:31 -0700
***@***.***" ***@***.***> wrote:

>cmake should look for Qt using a like like this:
>```
>find_package(Qt5 COMPONENTS Core Gui Svg Widgets REQUIRED)
>```
>
>It doesn't do this?
>
>
It doesn't need to. We make no use of QT!
The entire GUI is FLTK (+ Cairo for the Knobs).

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Tue, 02 May 2023 14:07:28 -0700
***@***.***" ***@***.***> wrote:

>No. The port still has this patch changing the default:
>```
>--- src/globals.h.orig  2023-02-19 18:22:47 UTC
>+++ src/globals.h
>@@ -126,8 +126,8 @@ typedef unsigned int  uint;
> #define DEFAULT_NAME "Simple Sound"
> #define UNTITLED "No Title"
> 
>-#define DEFAULT_AUDIO alsa_audio
>-#define DEFAULT_MIDI alsa_midi
>+#define DEFAULT_AUDIO jack_audio
>+#define DEFAULT_MIDI jack_midi
>  
> #define FORCED_EXIT 16
>```
>
>
I don't know who produces the port. It's not the main dev team.
Since V2.2.3 Audio default has been Jack.
MIDI is still ALSA. This is a difficult one to square, as Yoshimi is definitely
at it's best on Linux like this.

I suppose we could make both of these conditionally defined in Cmake. Ether
that, or detect the OS and change the definitions accordingly but we try to keep
as much as possible out of there. Besides I tend to regard Cmake as "Here Be
Dragons" country!

I'm currently starting to prepare for V 2.3.0 so will talk to the other devs to
see what we can come up with.

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Tue, 02 May 2023 14:07:28 -0700
***@***.***" ***@***.***> wrote:

>No. The port still has this patch changing the default:
>```
>--- src/globals.h.orig  2023-02-19 18:22:47 UTC
>+++ src/globals.h
>@@ -126,8 +126,8 @@ typedef unsigned int  uint;
> #define DEFAULT_NAME "Simple Sound"
> #define UNTITLED "No Title"
> 
>-#define DEFAULT_AUDIO alsa_audio
>-#define DEFAULT_MIDI alsa_midi
>+#define DEFAULT_AUDIO jack_audio
>+#define DEFAULT_MIDI jack_midi
>  
> #define FORCED_EXIT 16
>```
>

Are you aware you can force whatever options you like at runtime?
For example yoshimi -i -j -J
This will result in CLI and MIDI only (no GUI) Jack MIDI Jack audio

As usual for the full list yoshimi -?


-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
