### ISSUE TITLE
copyrighted material

### ISSUE THREAD

**Issue by umlaeute** [Yoshimi/yoshimi#184]
reviewing the licenses for the Debian package of Yoshimi, i have a couple of questions:
- `dev_notes/MPE_spec.pdf` appear to be non-free: it's copyright MMA, with all rights reserved, and explicitly forbidding re-distribution without a written permission. we in Debian do not have such a permission (so we cannot re-distribute the file). do you have such a permission? otherwise I suggest to remove the file either from the repository (or if you find this impractical), from the source tarballs
- where can I get the source code for `dev_notes/ControlModel.pdf`? (it's distributed under the GPL-2+, so I kindly ask you to provide the source code)
- the `doc/Histories.tar.bz2` file contains some non-dfsg-free files (namely the `splashreference.svg` which has a non-commercial clause). I'm not altogether sure what the purpose of the `doc/Histories.tar.bz2` archive is. it appears to include historic files (like new feature announcements) - is it supposed to be part of the releases, or is it just some place where you put stuff so you don't forget them? can it be omitted from the source tarballs? (otherwise, I will just have to remove it from the Debian sources)
. the `presets/`, `banks/` and `doc/examples/` (and therein most prominently the `Original Zyn Patchsets/`) contain non-code artifacts (which is totally fine). just to be sure: are they all covered by the GPL-2+ (or does some CC license apply)?

**Comment by abrolag** [comment]
sourceforge V2.3.0 tarball now updated with offending files removed.

-- 
Will J Godfrey

**Comment by umlaeute** [comment]
thanks, for the clarification, that's great (not that I doubted anything ;-))

you can remove specific files via the `.gitattribute` file (github generates it's tarball with `git archive`).

somebody already configured it to exclude the repository configuration: https://github.com/Yoshimi/yoshimi/blob/ace3cdd1dc26d37c8016869951a7cf36fbf9004f/.gitattributes#L3-L4

ad "SVG attached": i don't think github's mail interface allows for attachements. you can either attach a file via the webinterface, or (preferably) add it to the sources

ad "Histories": any specific reason why you put that into a tbz?
- the uncompressed files are much easier to access: e.g. via the webinterface, or a simple use of `less`. using an archive requires the users to go through an extra hoop.
- updating a compressed tarball is much more complicated than just adding/removing/modifying text file (which you have to do anyways)
- storing a compressed tarball that gets updated regularly makes the git history (of the tarball) much less useful
- the compressed tarball is 220kB, the extracted files cover 770kB. so while you technically only need a ¼ of the space, it's not that there is much space to save to start with.
- tracking a compressed tarball with git (that gets updated regularly) will probably take "much" more space in the git-repository: adding a single 800 byte file will give you a new 220kB tarball: git cannot compress that archive very well (whereas it could compress the single file much better). so I presume that whenever you change the Histories.tbz, the git repository grows "significantly" (again: the sizes we are taking about are not really relevant...I'm just trying to show that this is not helping *at all*). but then: i have not really tested this, so it's pure speculation.

**Comment by abrolag** [comment]
Ho-Hum :(
BugFix release V2.3.0.1 is now up there. Fixes errors in the new theme code.
At the same time I've made all the changes we discussed.

-- 
Will J Godfrey {apparently now an 'elderly'}
