### ISSUE TITLE
cmake seems to have a sporadic file copying dependency issue

### ISSUE THREAD

**Issue by nekopsykose** [Yoshimi/yoshimi#185]
when using the default `cmake -G "Unix Makefiles"`, there is some probability that the build then fails:  

```
-- Build files have been written to: /home/buildozer/aports/testing/yoshimi/src/yoshimi-2.3.0.1/build
[  1%] Generating VirKeyboardUI.cpp
[  1%] Generating ADnoteUI.cpp
[  1%] Built target yoshimi_lv2_ttl
[  2%] Generating BankUI.cpp
[  3%] Copying generated fluid sources: VirKeyboardUI.h, VirKeyboardUI.cpp
[  3%] Copying generated fluid sources: ADnoteUI.h, ADnoteUI.cpp
[  4%] Copying generated fluid sources: BankUI.h, BankUI.cpp
[  4%] Generating ConfigUI.cpp
[  5%] Generating ConsoleUI.cpp
[  5%] Copying generated fluid sources: ConfigUI.h, ConfigUI.cpp
Error copying file (if different) from "../ConfigUI.cpp" to ".".
[  5%] Copying generated fluid sources: ConsoleUI.h, ConsoleUI.cpp
make[2]: *** [LV2_Plugin/CMakeFiles/yoshimi_lv2.dir/build.make:99: LV2_Plugin/ConfigUI.cpp] Error 1
make[2]: *** Waiting for unfinished jobs....
[  5%] Copying generated fluid sources: EffUI.h, EffUI.cpp
Error copying file (if different) from "../EffUI.cpp" to ".".
make[2]: *** [LV2_Plugin/CMakeFiles/yoshimi_lv2.dir/build.make:129: LV2_Plugin/EffUI.cpp] Error 1
Error copying file (if different) from "../ConsoleUI.h" to ".".
make[2]: *** [LV2_Plugin/CMakeFiles/yoshimi_lv2.dir/build.make:165: LV2_Plugin/ConsoleUI.cpp] Error 1
make[2]: *** Deleting file 'LV2_Plugin/ConsoleUI.cpp'
make[1]: *** [CMakeFiles/Makefile2:180: LV2_Plugin/CMakeFiles/yoshimi_lv2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

if using the Ninja generator however, this can be easily reproduced with 100% certainty (`cmake -G Ninja`):  

```
-- Build files have been written to: /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/build
[1/206] cd /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/build/LV2_Plugin && test -f /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/src/LV2_Plugin/manifest.ttl && test -f /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/src/LV2_Plugin/yoshimi.ttl
[2/206] Generating VirKeyboardUI.cpp
[3/206] Generating VectorUI.cpp
[4/206] Generating SUBnoteUI.cpp
[5/206] Generating ResonanceUI.cpp
[6/206] Generating PresetsUI.cpp
[7/206] Generating PartUI.cpp
[8/206] Generating ParametersUI.cpp
[9/206] Generating PADnoteUI.cpp
[10/206] Generating OscilGenUI.cpp
[11/206] Generating MidiLearnUI.cpp
[12/206] Generating MicrotonalUI.cpp
[13/206] Generating MasterUI.cpp
[14/206] Generating MasterMiscUI.cpp
[15/206] Generating LFOUI.cpp
[16/206] Generating FilterUI.cpp
[17/206] Copying generated fluid sources: MidiLearnUI.h, MidiLearnUI.cpp
ninja: job failed: cd /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/build/LV2_Plugin && /usr/bin/cmake -E copy_if_different ../MidiLearnUI.cpp . && /usr/bin/cmake -E copy_if_different ../MidiLearnUI.h .
Error copying file (if different) from "../MidiLearnUI.cpp" to ".".
ninja: subcommand failed
```

this seems to be caused by some dependency issue between what generates the ui.cpp files from their source in cmake, though i'm not sure what the fix is

**Comment by abrolag** [comment]
Does this still happen if you go via ccmake to perform the initial setup?


My usual recommended setup is (within the base directory)
mkdir build
cd build
ccmake ../src
(within ccmake) set "build for this cpu"
c
g


-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by nekopsykose** [comment]
yes, that part is about the cmake generation part, but doesn't affect what is output and then the resulting `make` build failing

**Comment by nekopsykose** [comment]
also slight update: `cmake -G Ninja` with the official ninja (https://github.com/ninja-build/ninja) works fine, it only reproduces that 100% with (https://github.com/michaelforney/samurai), but both are not doing anything wrong- samurai's stack-based scheduler to make the last job first is what breaks this 100% of the time (which still means the build deps are invalid, even if one doesn't normally happen to see it)

**Comment by nekopsykose** [comment]
from the look of it, this happens because in:  

```
foreach(basename ${FltkUI_names})
    set (fluidfile "${CMAKE_CURRENT_SOURCE_DIR}/../UI/${basename}.fl")
    set (sourcefile "${basename}.cpp")
    set (headerfile "${basename}.h")
    add_custom_command(
      OUTPUT ${sourcefile}
      WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
      COMMAND ${CMAKE_COMMAND} ARGS -E copy_if_different "../${sourcefile}" .
      COMMAND ${CMAKE_COMMAND} ARGS -E copy_if_different "../${headerfile}" .
      DEPENDS ${fluidfile}
      COMMENT "Copying generated fluid sources: ${headerfile}, ${sourcefile}"
    )
    set (FltkUI_sources ${FltkUI_sources} "${sourcefile}")
    set (FltkUI_headers ${FltkUI_headers} "${headerfile}")
endforeach(basename ${FltkUI_names})
```

the `custom_command` depends on the `fluidfile` (.fl), but actually copies the generated .cpp/.h. this means it can run when the .fl exists but before it was actually generated.

this is easily apparent with samurai and building non-parallely, with `-j1`:  

```
ninja: entering directory 'build'
[1/206] cd /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/build/LV2_Plugin && test -f /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/src/LV2_Plugin/manifest.ttl && test -f /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/src/LV2_Plugin/yoshimi.ttl
[2/206] Copying generated fluid sources: MidiLearnUI.h, MidiLearnUI.cpp
ninja: job failed: cd /home/demon/src/aports/testing/yoshimi/src/yoshimi-2.3.0.1/build/LV2_Plugin && /usr/bin/cmake -E copy_if_different ../MidiLearnUI.cpp . && /usr/bin/cmake -E copy_if_different ../MidiLearnUI.h .
Error copying file (if different) from "../MidiLearnUI.cpp" to ".".
ninja: subcommand failed
```

where indeed that copy is the first thing that happens- since it doesn't actually depend on the generated files.

**Comment by abrolag** [comment]
On Fri, 16 Jun 2023 12:39:00 -0700
alice ***@***.***> wrote:

>also slight update: `cmake -G Ninja` with the official ninja (https://github.com/ninja-build/ninja) works fine, it only reproduces that 100% with (https://github.com/michaelforney/samurai), but both are not doing anything wrong- samurai's stack-based scheduler to make the last job first is what breaks this 100% of the time (which still means the build deps are invalid, even if one doesn't normally happen to see it)
>
I've just noticed  I'd left the CmakeLists.txt version I use for quicker UI
development in place. Yoshimi 2.3.0.2 has the correct release version.
Is this any better?

-- 
Will J Godfrey {apparently now an 'elderly'}

**Comment by nekopsykose** [comment]
it seems to have the same problem. the main issue is `src/CMakeLists.txt` has the custom_command that invokes `fluid` to generate the sourcefile from the fluidfile, but then src/LV2_Plugin/CMakeLists.txt has a custom_command that depends on just the fluidfile but actually copies the sourcefile generated from the prior command.

a (somewhat poor) workaround is to make the second custom_command  

```
    add_custom_command(
      OUTPUT ${sourcefile}
      WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
      COMMAND ${FLTK_FLUID_EXECUTABLE} ARGS -c -o .cpp ${fluidfile}
      DEPENDS ${fluidfile}
      COMMENT "Copying generated fluid sources: ${headerfile}, ${sourcefile}"
    )
```

which has the issue of generating the same thing twice (the list of fltk sources get fluid invoked on them a second time). it does work, but i think the OUTPUT/DEPENDS probably need tweaking instead.

my first guess was to DEPENDS on the `${sourcefile}` (since what it's really doing is just copying something previously generated), but that is apparently a circular dependency with something..

**Comment by abrolag** [comment]
Hmmm.
I wonder if this is connected with the LV2 code. That uses copied UI files.
Does disabling LV2 in cmake make any difference?

**Comment by abrolag** [comment]
I really must read comments more slowly :)

**Comment by abrolag** [comment]
OK I think I've got it!
The LV2 cmake file is the wrong one!

add_custom_command(
      OUTPUT ${sourcefile}
      WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
      COMMAND ${CMAKE_COMMAND} ARGS -E copy_if_different "../${sourcefile}" .
      COMMAND ${CMAKE_COMMAND} ARGS -E copy_if_different "../${headerfile}" .
      DEPENDS ${fluidfile}
      COMMENT "Copying generated fluid sources: ${headerfile}, ${sourcefile}"
    )

should be just:

add_custom_command(
      OUTPUT ${sourcefile}
      COMMAND ${FLTK_FLUID_EXECUTABLE} ARGS -c -o .cpp ${fluidfile}
      DEPENDS ${fluidfile}
    )

**Comment by nekopsykose** [comment]
yeah, that works, but does generate it twice. the probably correct solution is to remove that entirely and reuse the same `FltkUI_sources` in the lv2_plugin as in the base file, but for some reason cmake refuses to understand the cpp files are generated.. (which is probably why you copied them in the first place)

**Comment by nekopsykose** [comment]
new source works, though note you retagged 2.3.0.2 instead of making it .3 .

thanks!

**Comment by abrolag** [comment]
On Fri, 16 Jun 2023 16:31:56 -0700
alice ***@***.***> wrote:

>new source works, though note you retagged 2.3.0.2 instead of making it .3 .
>
>thanks!
>

Glad it's resolved now.
Yes. I hoped to sneak that in without anyone noticing - it's more of what
should have been in the previous commit :o

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
