### ISSUE TITLE
Error: Can't find PDF manual :-(

### ISSUE THREAD

**Issue by zizlog** [Yoshimi/yoshimi#186]
Yoshimi looks for the PDF in /usr/share/doc/yoshimi and alternatively in /usr/local/share/doc/yoshimi but it can't find the PDF (named yoshimi-advanced-reference-manual.pdf) in neither location by printing "Can't find PDF manual :-("
The PDF is from ahlstromcj/yoshimi-doc at Github. There is no default/ old pdf installed in Yoshimi.
What does "Can't find last PDF. Looking for older one" in Interchange.cpp mean?

Alongside that, is it possible to CHG from /usr/share/doc/yoshimi to /usr/share/doc/packages/yoshimi/doc where all the other docs of Yoshimi are located? The */doc/packages/ location seams to be commonly used by the mayority of packages.

It might be a separate issue but will post here since it is related.
How do you access the html docs from the GUI version of Yoshimi? All I find is "View Manual" in the Yoshimi menu tab which leads to the Error.

Yoshimi v2.3.0.1

**Comment by abrolag** [comment]
On Mon, 17 Jul 2023 02:11:14 -0700
zizlog ***@***.***> wrote:

>Yoshimi looks for the PDF in /usr/share/doc/yoshimi and alternatively in /usr/local/share/doc/yoshimi but it can't find the PDF (named yoshimi-advanced-reference-manual.pdf) in neither location by printing "Can't find PDF manual :-("
>The PDF is from ahlstromcj/yoshimi-doc at Github. There is no default/ old pdf installed in Yoshimi.
>What does "Can't find last PDF. Looking for older one" in Interchange.cpp mean?
>
>Alongside that, is it possible to CHG from /usr/share/doc/yoshimi to /usr/share/doc/packages/yoshimi/doc where all the other docs of Yoshimi are located? The */doc/packages/ location seams to be commonly used by the mayority of packages.
>
>It might be a separate issue but will post here since it is related.
>How do you access the html docs from the GUI version of Yoshimi? All I find is "View Manual" in the Yoshimi menu tab which leads to the Error.
>

Which distro are you running? /usr/doc/packages doesn't exist in debian (nor any
debian based ones I know of).

Yoshimi does a search through the *known* locations to find the HTML guide, and
if that fails tries looking for the older PDF manual (which is no longer
distributed due to its size). This is to hopefully cover the situation where
someone has been regularly updating from much older Yoshimi versions. We should
probably change the wording, or even remove it completely.

If all else fails the HTML guide can be found at:
http://yoshimi.github.io/docs/user-guide

The Advanced Reference Manual can be downloaded from:
https://github.com/Yoshimi/yoshimi-doc/raw/master/pdf/yoshimi-advanced-reference-manual.pdf

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by zizlog** [comment]
> Which distro are you running? /usr/doc/packages doesn't exist in debian (nor any
debian based ones I know of).

openSUSE, it's /usr/share/doc/packages

> Yoshimi does a search through the *known* locations to find the HTML guide

The HTML guide is in /usr/share/doc/packages/yoshimi/doc/yoshimi_user_guide/

> if that fails tries looking for the older PDF manual (which is no longer
distributed due to its size).

That's understandable. I'm fine with copying the PDF to it's needed location for the menu entry to work.

The error msg could include the path where the PDF should be as a possible solution.

The download location for the Advanced reference manual you provided is the same manual as in https://github.com/ahlstromcj/yoshimi-doc/blob/master/pdf/yoshimi-advanced-reference-manual.pdf, only the date differs by a couple days.

What can be a reason it doesn't find the PDF in either of the _known_ locations neither does it find the HTML?

**Comment by abrolag** [comment]
On Mon, 17 Jul 2023 07:11:57 -0700
zizlog ***@***.***> wrote:

>> Which distro are you running? /usr/doc/packages doesn't exist in debian (nor any  
>debian based ones I know of).
>
>openSUSE, it's /usr/share/doc/packages
>
>> Yoshimi does a search through the *known* locations to find the HTML guide  
>
>The HTML guide is in /usr/share/doc/packages/yoshimi/doc/yoshimi_user_guide/
>
>> if that fails tries looking for the older PDF manual (which is no longer  
>distributed due to its size).
>
>That's understandable. I'm fine with copying the PDF to it's needed location for the menu entry to work.
>
>The error msg could include the path where the PDF should be as a possible solution.

Good point.

>The download location for the Advanced reference manual you provided is the
>same manual as in
>https://github.com/ahlstromcj/yoshimi-doc/blob/master/pdf/yoshimi-advanced-reference-manual.pdf,
>only the date differs by a couple days.

Yes. the ahlstromcj location is where any updates are done. The one in the main
Yoshimi location always tracks the latest release.

>What can be a reason it doesn't find the PDF in either of the _known_ locations neither does it find the HTML?

Are you saying it still can't find these when copied to the locations that
Yoshimi expects?

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by zizlog** [comment]
> Are you saying it still can't find these when copied to the locations that
Yoshimi expects?

Yes. 
1) `/usr/share/doc/yoshimi/` doesn't exist by default and 
2) `/usr/local/share/doc/yoshimi/` is empty.

Case 1:
created yoshimi sub-directory and copied pdf there,
`ll /usr/share/doc/yoshimi/
total 7028`
`-rw-r--r-- 1 root root 7192761 Jul 30 17:10 yoshimi-advanced-reference-manual.pdf`

Starting yoshimi in the terminal and selecting the menu entry "View Manual":

`Yay! We're up and running :-)`
`Found 880 instruments in 24 banks`
`Root 1. Bank set to 5 "Arpeggios"`
`yoshimi> Can't find manual :(`
`Can't find PDF manual :(`
`kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found`

Case 2:
copied same pdf to 
`ll /usr/local/share/doc/yoshimi/
total 7028`
`-rw-r--r-- 1 root root 7192761 Jul 30 17:21 yoshimi-advanced-reference-manual.pdf`

Restarted yoshimi and selecting same menu entry as above results in the same error msg.

Why would the html manual be in  /usr/share/doc/packages/yoshimi/doc/yoshimi_user_guide/ for openSUSE but not for other distros?
I mean it makes sense when all other packages are there as well to keep it tidy and conform to the distro's standard.

I might set up a minimal VM to check other distros.

**Comment by abrolag** [comment]
On Sun, 30 Jul 2023 08:35:22 -0700
zizlog ***@***.***> wrote:

>> Are you saying it still can't find these when copied to the locations that  
>Yoshimi expects?
>
>Yes. 
>1) `/usr/share/doc/yoshimi/` doesn't exist by default and 
>2) `/usr/local/share/doc/yoshimi/` is empty.
>
>Case 1:
>created yoshimi sub-directory and copied pdf there,
>`ll /usr/share/doc/yoshimi/
>total 7028`
>`-rw-r--r-- 1 root root 7192761 Jul 30 17:10 yoshimi-advanced-reference-manual.pdf`
>
>Starting yoshimi in the terminal and selecting the menu entry "View Manual":
>
>`Yay! We're up and running :-)`
>`Found 880 instruments in 24 banks`
>`Root 1. Bank set to 5 "Arpeggios"`
>`yoshimi> Can't find manual :(`  
>`Can't find PDF manual :(`
>`kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found`
>
>Case 2:
>copied same pdf to 
>`ll /usr/local/share/doc/yoshimi/
>total 7028`
>`-rw-r--r-- 1 root root 7192761 Jul 30 17:21 yoshimi-advanced-reference-manual.pdf`
>
>Restarted yoshimi and selecting same menu entry as above results in the same error msg.
>
>Why would the html manual be in  /usr/share/doc/packages/yoshimi/doc/yoshimi_user_guide/ for openSUSE but not for other distros?
>I mean it makes sense when all other packages are there as well to keep it tidy and conform to the distro's standard.
>
>I might set up a minimal VM to check other distros.
>

First off, I've no idea why openSUSE has used that location. I've not seen such
a thing in any other distro. This makes me wonder where they've put everything
else - especially default instrument banks!

Secondly, the fall-back to looking for the PDF manual was only intended as a
temporary measure while the transition was taking place across releases. That
was two years ago - we should have removed it by now!

The HTML guide actually includes a link for fetching the PDF advanced one.
Also the HTML one is always the most up-to-date, and most usable for quick
reference.

The full paths where Yoshimi will expect to find this are in order of priority:

/home/{user}/yoshimi-code/doc/yoshimi_user_guide {self build}
/usr/local/share/doc/yoshimi/yoshimi_user_guide {self built and installed}
/usr/share/doc/yoshimi/yoshimi_user_guide {distro install}

Originally we tried doing a system-wide search, but that was excruciatingly
slow - even when we limited the search to /usr/share and /usr/local/share

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
Finding the manual is now handled (since V2.3.1.2) quite differently, and should find the latest copy just about anywhere. It is done only when there's a version change, and in a separate thread so that it doesn't slow the start of Yoshimi.
I'll leave this open for a while to give people time to see it.
