### ISSUE TITLE
[BUG] several windows don't have "Yoshimi" in the name and are always opened maximum size in a tiling WM

### ISSUE THREAD

**Issue by zizlog** [Yoshimi/yoshimi#187]
Using a tiling WM you can ignore or float window with specific classes,  names or roles from being tiled. 
Having added Yoshimi to names in "Float Windows" it works for most of Yoshimi's windows but not for:
1. Bank Search
2. Scales
3. Recent {Instruments|Sets|States|Scales}

They are all tiled with maximum size behind all other Yoshimi windows.

Desired behavior: like the windows with "Yoshimi" in the title.

**Comment by abrolag** [comment]
On Mon, 17 Jul 2023 07:27:48 -0700
zizlog ***@***.***> wrote:

>Using a tiling WM you can ignore or float window with specific classes,  names or roles from being tiled. 
>Having added Yoshimi to names in "Float Windows" it works for most of Yoshimi's windows but not for:
>1. Bank Search
>2. Scales
>3. Recent {Instruments|Sets|States|Scales}
>
>They are all tiled with maximum size behind all other Yoshimi windows.
>
>Desired behavior: like the windows with "Yoshimi" in the title.
>

The 'Yoshimi' prefix was dropped from these windows as they are quite narrow
and difficult to read with the full title. Presumably this means your WM
doesn't recognise them as part of Yoshimi. I'll see what can be done about it.

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
Hmmm. Scales *does* have Yoshimi in the title, so there's something else causing this.
Can you see if things like the freemode envelope or formant filter editor windows also do this?

**Comment by zizlog** [comment]
> Scales does have Yoshimi in the title, so there's something else causing this.

Yes, Scales does, it's Recent Scales which doesn't have Yoshimi in the title.

> Can you see if things like the freemode envelope or formant filter editor windows also do this?

What or rather where exactly is the freemode env and the formant filter? 

I find Yoshimi still difficult to navigate due to its complexity and all windows being the color. Customizing colors in a custom theme doesn't seem to be as easy as I thought.

**Comment by abrolag** [comment]
On Sun, 30 Jul 2023 08:48:41 -0700
zizlog ***@***.***> wrote:

>> Scales does have Yoshimi in the title, so there's something else causing this.  
>
>Yes, Scales does, it's Recent Scales which doesn't have Yoshimi in the title.
>
>> Can you see if things like the freemode envelope or formant filter editor windows also do this?  
>
>What or rather where exactly is the freemode env and the formant filter? 
>
>I find Yoshimi still difficult to navigate due to its complexity and all windows being the color. Customizing colors in a custom theme doesn't seem to be as easy as I thought. 

OK, well go for the easiset one Bank Search.
Frst off go to /src/UI/BankUI.fl

At line 544 change:
label {Bank Search}

to:
label {Yoshimi: Bank Search}

Recompile, then see if that now behaves as wanted.

If that works there are several others that are likely to need changing.

In the AddSynth window click on the 'E' button in the Envelope panel to
display the Freemode window.
Also try the dark blue 'C' and 'P' buttons.
I'm expecting these to have the same problem.

Another likely one is in the Filter panel.
Use its menu to change analog to formant, then click on the Edit button that
appears. This will show the formant editor.

The dropdown menu entries are likely be a bit more complicated :(


Making individual windows different colours would be extremely complex. There
are all built with the same structures.

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Mon, 17 Jul 2023 07:27:48 -0700
zizlog ***@***.***> wrote:

>Using a tiling WM you can ignore or float window with specific classes,  names or roles from being tiled. 
>Having added Yoshimi to names in "Float Windows" it works for most of Yoshimi's windows but not for:
>1. Bank Search
>2. Scales
>3. Recent {Instruments|Sets|States|Scales}
>
>They are all tiled with maximum size behind all other Yoshimi windows.
>
>Desired behavior: like the windows with "Yoshimi" in the title.
>
Should be OK in the latest build V 2.3.0.3

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
