### ISSUE TITLE
XML: Could not load xml file: /usr/share/yoshimi/banks/chip/0043-BigBass5.xmz

### ISSUE THREAD

**Issue by Grahack** [Yoshimi/yoshimi#199]
Hi,
I'm launching yoshimi with:  
`yoshimi --no-gui --load=/usr/share/yoshimi/banks/chip/0043-BigBass5.xiz --alsa-audio hw:1`
and I get this message:
```
Yoshimi 1.5.6 is starting
Error, alsa audio: alsa audio mmap not possible: Invalid argument
March little endian = 1
Format = Signed Little Endian 32 Bit 2 Channel
Using alsa_audio for audio and alsa_midi for midi
XML: Failed to open xml file /usr/share/yoshimi/banks/chip/0043-BigBass5.xmz for load, errno: 2  No such file or directory
XML: Could not load xml file: /usr/share/yoshimi/banks/chip/0043-BigBass5.xmz
Failed to load parameters /usr/share/yoshimi/banks/chip/0043-BigBass5.xmz
Alsa audio priority is 40
Alsa midi priority is 39
Yoshimi 1.5.6
Build Number 1214
Clientname: yoshimi
Audio: alsa -> 'default'
Midi: alsa -> 'default'
Oscilsize: 512
Samplerate: 48000
Period size: 256

Yay! We're up and running :-)
```
Then I've got the sine sound OK.

I guess the xiz on my disk has been installed with yoshimi, but there is not any xmz file for sure on my disk.
How is it that yoshimi looks for an xmz file?
Thanks.

**Comment by abrolag** [comment]
On Thu, 22 Feb 2024 13:01:06 -0800
Prof Gra ***@***.***> wrote:

>Hi,
>I'm launching yoshimi with:  
>`yoshimi --no-gui --load=/usr/share/yoshimi/banks/chip/0043-BigBass5.xiz --alsa-audio hw:1`
>and I get this message:
>```
>Yoshimi 1.5.6 is starting
>Error, alsa audio: alsa audio mmap not possible: Invalid argument
>March little endian = 1
>Format = Signed Little Endian 32 Bit 2 Channel
>Using alsa_audio for audio and alsa_midi for midi
>XML: Failed to open xml file /usr/share/yoshimi/banks/chip/0043-BigBass5.xmz for load, errno: 2  No such file or directory
>XML: Could not load xml file: /usr/share/yoshimi/banks/chip/0043-BigBass5.xmz
>Failed to load parameters /usr/share/yoshimi/banks/chip/0043-BigBass5.xmz
>Alsa audio priority is 40
>Alsa midi priority is 39
>Yoshimi 1.5.6
>Build Number 1214
>Clientname: yoshimi
>Audio: alsa -> 'default'
>Midi: alsa -> 'default'
>Oscilsize: 512
>Samplerate: 48000
>Period size: 256
>
>Yay! We're up and running :-)
>```
>Then I've got the sine sound OK.
>
>I guess the xiz on my disk has been installed with yoshimi, but there is not any xmz file for sure on my disk.
>How is it that yoshimi looks for an xmz file?
>Thanks.
>
The answer is you've told it to load a patch set / parameters file!

For a single instrument it should have been:
yoshimi --no-gui
--load-instrument=/usr/share/yoshimi/banks/chip/0043-BigBass5.xiz
--alsa-audio hw:1

Incidentally, that is a very old version of Yoshimi. It came out in the latter
half of 2017.

Debian and Ubuntu are currently showing V2.3.1, and V2.3.2 is available to
self builders.

P.S. Sorry my mail reader is auto-wrapping lines :(

-- 
Will J Godfrey {apparently now an 'elderly'}
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by Grahack** [comment]
Many thanks for this helpful answer.
Regarding the version this is the one my (broken) package manager offers and the one on my Raspberry Pi is even older (realtime distro from the imager). I'll try to update soonish.
