### ISSUE TITLE
crash with jack

### ISSUE THREAD

**Issue by oddtime** [Yoshimi/yoshimi#206]
Hi ! :)
when I have started jack from qjackctrl, if I start yoshimi it doesn't play nor appear in the jack connections. Then if I want to close it it seems to crash, its windows remaining inactive. As I stop Jack, Yoshimi is terminated.

Any hints on the jack use?

Thank you

**Comment by abrolag** [comment]
On Sat, 10 Aug 2024 16:31:52 -0700
Stefano Carbonelli ***@***.***> wrote:

>Hi ! :)
>when I have started jack from qjackctrl, if I start yoshimi it doesn't play nor appear in the jack connections. Then if I want to close it it seems to crash, its windows remaining inactive. As I stop Jack, Yoshimi is terminated.
>
>Any hints on the jack use?
>
>Thank you
>

What distro is this on?

Which version of Yoshimi are you using?
Is it from the distro or did you build it.

What happens if you try starting from the command line with:
yoshimi -J

-- 
Will J Godfrey

**Comment by oddtime** [comment]
> Which version of Yoshimi are you using?
> Is it from the distro or did you build it.

1.7.0.1 rom the distro, lubuntu 20.

> What happens if you try starting from the command line with:
> yoshimi -J
> 

It works now!
I reboot, tried `yoshimi -J` and it worked.
After that command yoshimi works also when called by the app menu and it is shown in the audio connections of qjackctl...

Thank you very much.
