### ISSUE TITLE
libz not found on Ubuntu 16.04

### ISSUE THREAD

**Issue by sabrehagen** [Yoshimi/yoshimi#26]
Hi,

I'm getting the following error when using ccmake to configure:
```sh
 CMake Error at CMakeLists.txt:133 (message):
   libz required but not found:
```
I've installed all dependencies listed in the `Dependencies` file, and my installed packages relating specifically to zlib are as follows:

```sh
$ apt list --installed | grep zlib
zlib1g/xenial,now 1:1.2.8.dfsg-2ubuntu4 amd64 [installed]
zlib1g-dev/xenial,now 1:1.2.8.dfsg-2ubuntu4 amd64 [installed]
```

Can you give me some advice as to what I might need to get the build working?

Ultimately I have no need to build from source; a Ubuntu specific release would make my life great :) If you need any more information to help me diagnose please let me know.

Thanks

**Comment by abrolag** [comment]
On Mon, 10 Apr 2017 19:40:28 -0700
Jackson Delahunt <notifications@github.com> wrote:

> Hi,
> 
> I'm getting the following error when using ccmake to configure:
> ```sh
>  CMake Error at CMakeLists.txt:133 (message):
>    libz required but not found:
> ```
> I've installed all dependencies listed in the `Dependencies` file, and my installed packages relating specifically to zlib are as follows:
> 
> ```sh
> $ apt list --installed | grep zlib
> zlib1g/xenial,now 1:1.2.8.dfsg-2ubuntu4 amd64 [installed]
> zlib1g-dev/xenial,now 1:1.2.8.dfsg-2ubuntu4 amd64 [installed]
> ```
> 
> Can you give me some advice as to what I might need to get the build working?
> 
> Ultimately I have no need to build from source; a Ubuntu specific release would make my life great :) If you need any more information to help me diagnose please let me know.
> 
> Thanks
> 

This is rather strange.

What version of yoshimi are you trying to build?

Have you tried deleting CMakeCache.txt and starting again? - it sometimes gets
confused.

Try checking the sanity of the locations of zlib.h and zlib.so

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by sabrehagen** [comment]
I was unfamiliar with `ccmake`. Removing CMakeCache.txt fixed it. Thanks.
