### ISSUE TITLE
Cmake error:  error: ‘margin_width’ is not a member of ‘Fl_Tooltip’      _w += Fl_Tooltip::margin_width() * 2

### ISSUE THREAD

**Issue by dsimak** [Yoshimi/yoshimi#27]
Hi Will!
I'm having this error in last master 1.5.1.1:

```
[ 50%] Building CXX object CMakeFiles/yoshimi.dir/UI/DynamicTooltip.cpp.o
/home/diego/Downloads/yoshimi-master/src/UI/DynamicTooltip.cpp: In member function ‘void DynTooltip::update()’:
/home/diego/Downloads/yoshimi-master/src/UI/DynamicTooltip.cpp:227:11: error: ‘margin_width’ is not a member of ‘Fl_Tooltip’
     _w += Fl_Tooltip::margin_width() * 2;
           ^
/home/diego/Downloads/yoshimi-master/src/UI/DynamicTooltip.cpp:228:11: error: ‘margin_height’ is not a member of ‘Fl_Tooltip’
     _h += Fl_Tooltip::margin_height() * 2;
           ^
/home/diego/Downloads/yoshimi-master/src/UI/DynamicTooltip.cpp: In member function ‘virtual void DynTooltip::draw()’:
/home/diego/Downloads/yoshimi-master/src/UI/DynamicTooltip.cpp:241:20: error: ‘margin_width’ is not a member of ‘Fl_Tooltip’
     const int mw = Fl_Tooltip::margin_width();
                    ^
/home/diego/Downloads/yoshimi-master/src/UI/DynamicTooltip.cpp:242:20: error: ‘margin_height’ is not a member of ‘Fl_Tooltip’
     const int mh = Fl_Tooltip::margin_height();
                    ^
make[2]: *** [CMakeFiles/yoshimi.dir/UI/DynamicTooltip.cpp.o] Error 1
make[1]: *** [CMakeFiles/yoshimi.dir/all] Error 2
make: *** [all] Error 2
```

**This error was not observed in 1.5.0 rc5**
This is the result after "cmake .":

```
diego@ruidosa:~/Downloads/yoshimi-master/src$ cmake .
-- Building Yoshimi version 1.5.1 M for Linux
-- Found pkg-config /usr/bin/pkg-config
-- Found libz
-- Found fftw3f 3.3
-- Found mxml 2.6
-- Found Alsa 1.0.25
-- Found jack 1.9.9.5
-- Found boost headers version 104800
-- Found fontconfig 2.8.0
-- Found libcairo 1.10.2
-- Found FLTK
-- Found libncurses or libncursesw
-- Readline library found
-- Building for Release, flags: -O3 -msse -msse2 -mfpmath=sse -ffast-math -fomit-frame-pointer
-- With jack session support
-- Found lv2 package 1.10.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/diego/Downloads/yoshimi-master/src
```

I suspect that this issue could be related to current fltk version.

Let me know any other info you may need.

Thank you.
Diego

**Comment by abrolag** [comment]
Hi Diego,

Sorry to see you're having problems.

A couple of guys have been doing a lot with tooltips and it's possible we've
gone a bit too far. It seems margin controls only appeared with fltk version
1.3.2. What version do you have?

If you can't upgrade, try the following in 'src/UI/DynamicToolTips.cpp'.

Change lines,227,228, 241, 242

From:
    _w += Fl_Tooltip::margin_width() * 2;
    _h += Fl_Tooltip::margin_height() * 2;

    const int mw = Fl_Tooltip::margin_width();
    const int mh = Fl_Tooltip::margin_height();

To:
    _w += 8;
    _h += 8;

    const int mw = 4;
    const int mh = 4;

Meanwhile I'll get onto the others and we'll see if we can find a proper fix.

Will.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by dsimak** [comment]
Hey Will!
No problem at all, it's a pleasure to contribuite in some way to yoshimi.

I have fltk 1.3.0.
I've tried to upgrade to 1.3.4 but I had some nasty errors during linking so I've reverted to 1.3.0.

So:
I've applied your changes and it's solved, up and running!

I going to investigate the proper way to upgrade fltk.

Thank you very much for your help!

Diego

**Comment by abrolag** [comment]
In the latest build we've reverted to fixed size margins for the foreseeable future.
I'll leave this up for a week or two, then close it.

**Comment by dsimak** [comment]
Thanks Will,
Unfortunately I could not upgrade ftlk version in a simple way.... (it's an
old Ubuntu 12.04 I know but it's still working...)

I will try last build and I'll let you know.

Thanks.
Diego


2017-05-03 15:10 GMT-03:00 Will J Godfrey <notifications@github.com>:

**Comment by dsimak** [comment]
I've downloaded last build and no problems were observed during make.

Thank you Will!

Diego


2017-05-03 16:02 GMT-03:00 Diego Simak <diego.simak@gmail.com>:
