### ISSUE TITLE
Implement LV2_STATE__StateChanged

### ISSUE THREAD

**Issue by danvd** [Yoshimi/yoshimi#29]

**Comment by danvd** [comment]
Hi Will,
The task is done. I added a new branch named 'staging' for testing.
The same is true for muse - the same branch 'staging' where all new changes reside.

I'm waiting for your test results :)
Here is the issue for muse project:
https://github.com/muse-sequencer/muse/issues/565

**Comment by abrolag** [comment]
This seems to work fine with Muse, although some of Yoshimi's controls aren't fully exposed yet so those won't be seen of course.

However, I just fetched the latest version of qtractor and they claim to support this now as well, but it doesn't seem recognise changes in Yoshimi.

I don't know of any other plugins this can be tested with for comparisons.

**Comment by danvd** [comment]
Ok, I looked at qtractor's source - it seems, that this event must be handled only when something in gui changes. I'll make it this way too.

**Comment by abrolag** [comment]
OK.
(state | 0x20) if I remember right :)

**Comment by danvd** [comment]
Ok, I think, that last commits to yoshimi and muse staging branch should do the work. 
P.S. some info - in qtractor the ui port write function is also called from an audio thread for ordinal lv2 output ports. So my first implementation was very close to the right one except one small error. Now muse and qtractor can catch state changed event in the common way :)

**Comment by abrolag** [comment]
Yes this works fine now. I also went through the pain of getting the latest version of Ardour (boy do they like making obscure changes!) and it is compatible there too - no surprise as I know the originator has close ties with the Ardour team - so we now have complete compatibility across the major hosts :)

P.S.
I've made a small change to write detection -explained in the code.

**Comment by danvd** [comment]
Sounds good :). Closing this issue now.
