### ISSUE TITLE
--no-cmdline ignored

### ISSUE THREAD

**Issue by kjyv** [Yoshimi/yoshimi#30]
I want to run yoshimi in a headless setup and hence call it with the --no-cmdline option (I do want to use its output messages though in case of errors). Regardless of the option, it gives me the yoshimi> prompt. This is an issue for me because it actually constantly prints "yoshimi>" when run with appended & from a bash script. The printing has not been a problem with at least version 1.2.4 (I didn't test all versions in between)

**Comment by abrolag** [comment]
This is a known problem and on my to-do list.
It only occurred when we moved the prompt line because other CLI users were *not* seeing it when they needed to.

I've only just got back from LAC2017, so give me time to get back in gear.

**Comment by kjyv** [comment]
Sure, no worries! Btw, I've noticed there is logic in the code that assumes either gui or command line has to be there, so if both is disabled it enables command line. I think if both options are set, both should be disabled. For some reason bShowCmdLine is however 1 (in main.cpp:347) even if -no-cmdline is set. If I comment out starting the cmdline thread (main.cpp:394), I get the expected behavior.

**Comment by abrolag** [comment]
Just checking some details.

If you have no CLI or GUI access, then that means you only have MIDI control. That seems rather limiting.

Also, how do you make a clean exit? Some settings, like recent history are only updated on a 'normal' exit.

**Comment by kjyv** [comment]
Yes, thats right. Using only midi control should be fine for switching banks/programs and turning the knobs that are connected to the midi controller (previously, with gui). I'd like to have a setting where I don't have to touch any screen. A clean exit should be handled when the proper signal is sent (SIGINT/SIGTERM).

**Comment by abrolag** [comment]
OK, this should be fixed in the current master.

**Comment by kjyv** [comment]
Hm, I get exactly the same behavior as before.

**Comment by abrolag** [comment]
Odd.
How are you starting Yoshimi?
The first time you want to run this way it should be yoshimi -c -i
Then if you exit cleanly the setting will be stored and you can start with just yoshimi

Are you sure you are running the latest build and not maybe an older one? Build number should be reported as  1034 when it starts

**Comment by kjyv** [comment]
Oh, sorry. The old state was still there, it works well now after deleting it. Thanks!
