### ISSUE TITLE
Support french BÉPO keymap

### ISSUE THREAD

**Issue by gordonzola** [Yoshimi/yoshimi#31]
Hi.

The multi-keymap support is great in Yoshimi. I would like to use it with my BÉPO layout (https://bepo.fr), which is kinda the french Dvorak keymap. Would it be possible to integrate it? Is there any documentation that I could use to provide a pull request for BÉPO support?

Thanks

**Comment by abrolag** [comment]
On Thu, 01 Jun 2017 05:47:47 -0700
Damien Nicolas <notifications@github.com> wrote:

> Hi.
> 
> The multi-keymap support is great in Yoshimi. I would like to use it with my BÉPO layout (https://bepo.fr), which is kinda the french Dvorak keymap. Would it be possible to integrate it? Is there any documentation that I could use to provide a pull request for BÉPO support?
> 
> Thanks
> 

Hi Damien,

I'd be happy to see this added. Unfortunately, there is no documentation, but
changing the layout is fairly simple, consisting of two declarations in
src/UI/VirKeyboardUI.fl. These are arrays of the lower-case characters
representing the wanted keys, and one or two key numbers instead, where needed.

There would also need to be the addition of another line in the menu in
src/UI/ConfigUI.fl

I don't think there is much else that would need to be changed.

I've not done anything with this myself (it was set up before I became involved)
but I have been thinking that the tooltip in the virtual keyboard should match
the actual selected one, so if you can think of a way to add that it'd be much
appreciated.

Best,

Will.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
Hi Damien,
Not heard any more from you. Were you able to get anywhere with this?

**Comment by abrolag** [comment]
Heard no more and can do nothing without information, so closing this.
