### ISSUE TITLE
Virtual keyboard: X key autorepeat gets in the way

### ISSUE THREAD

**Issue by unixpipecentipede** [Yoshimi/yoshimi#36]
Hello. I'm running a local build of Yoshimi 1.5.3.

When 'keyjazzing' on the computer's keyboard (QWERTY here), keeping a
key pressed down triggers the X server autorepeat feature with
annoying consequences.

As a workaround, this command effectively turns off autorepeat (for
all X clients though):

    xset r off

I have no idea if this can be replicated on other systems. I'm running
Devuan Jessie (which is based on Debian Jessie) with no desktop
environment nor display manager. Just dwm as window manager.

**Comment by abrolag** [comment]
It should work on all distros that use the X server. I've tried it on both debian and fedora.

**Comment by unixpipecentipede** [comment]
It is a good one indeed! Borrowed from music tracker's culture.

**Comment by abrolag** [comment]
I think everyone has had time to pick up this by now so I'm closing it.
