### ISSUE TITLE
Splash screen won't go away

### ISSUE THREAD

**Issue by magnetophon** [Yoshimi/yoshimi#39]
When I xkill it, yoshimi dies.
Version : 1.5.5
1.5.3 did not have this problem.

**Comment by abrolag** [comment]
On Tue, 12 Dec 2017 08:36:56 -0800
Bart Brouns <notifications@github.com> wrote:

>When I xkill it, yoshimi dies.
>
Is it staying in front, or does it allow other windows to be placed in front
of it?

If you uncheck the switch for it in Settings...>switches, does that stop it
appearing next time you start?

Are you running the actual release version or one of the rc ones?

What distro and window manager are you running?

Anyone else seeing this?

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by magnetophon** [comment]
> Is it staying in front, or does it allow other windows to be placed in front of it?

It allows other windows to be placed in front of it.

> If you uncheck the switch for it in Settings...>switches, does that stop it appearing next time you start?

Yes.

> Are you running the actual release version or one of the rc ones?

Release.

> What distro and window manager are you running?

NixOS with i3.

**Comment by abrolag** [comment]
On Tue, 12 Dec 2017 17:54:59 +0000 (UTC)
Bart Brouns <notifications@github.com> wrote:

>> Is it staying in front, or does it allow other windows to be placed in front of it?  
>
>It allows other windows to be placed in front of it.


Well that proves the updating routine times out correctly.

>> If you uncheck the switch for it in Settings...>switches, does that stop it appearing next time you start?  
>
>Yes.

And that proves it sees the appropriate switches.

>> Are you running the actual release version or one of the rc ones?  
>
>Release.

So it's after the known bug was fixed.

>> What distro and window manager are you running?  
>
>NixOS with i3.

I don't know that distro but can't think of anything that might be specific to
that one. What about the window manager itself? XFCE, Openbox, KDE, Gnome?

It's odd that it correctly times out but fails to hide the window. The commands
are cheek & jowl!

Anyone else have this problem?

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by magnetophon** [comment]
The distro is: https://nixos.org
The window manager is https://i3wm.org

**Comment by magnetophon** [comment]
The distro is: https://nixos.org
The window manager is https://i3wm.org

**Comment by abrolag** [comment]
On Tue, 12 Dec 2017 18:25:34 +0000 (UTC)
Bart Brouns <notifications@github.com> wrote:

>The distro is: https://nixos.org
>The window manager is https://i3wm.org
>
Oh I see. I thought you were referring to an Intel i3 core :)

This is very different from what I'm used to. I'll have to talk to the other
devs (I know one frequently builds in virtual environments).

Meanwhile I'm glad you can disable it for the time being.

I will make sure this doesn't get forgotten!

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by trebmuh** [comment]
Running 1.5.5 on a Debian Stretch + MATE desktop environment, I'm not having this issue.

**Comment by abrolag** [comment]
Can you try the current master please - I'm off for some serious Zzzz :)

**Comment by magnetophon** [comment]
Yes, that was it, thanks!

**Comment by abrolag** [comment]
There's a final update in the current master. Now using epoch time to avoid any ambiguities. Timeout is set for 3 seconds, with a 'define' at the top of src/main.cpp
