### ISSUE TITLE
Recent yoshimi crashes Carla and Qtractor when opening GUI

### ISSUE THREAD

**Issue by suedwestlicht** [Yoshimi/yoshimi#48]
I noticed it when I tried commit 6d9158128ea517f3cbdf75819e8d81e045f600e9 and newer.

Yoshimi LV2 works fine in Qtractor but crashes Qtracor (and Carla) when I try to open the GUI.

**Comment by suedwestlicht** [comment]
commit 15b7215e230ad74cc4ec507165bbcd2d96bb9b83 is the last version I tried and it doesn't crash Qtractor or Carla.

**Comment by suedwestlicht** [comment]
2019-03-01 is ok, 2019-04-01 crashes. Investigating further.

**Comment by abrolag** [comment]
On Tue, 30 Apr 2019 10:40:21 -0700
suedwestlicht <notifications@github.com> wrote:

>I noticed it when I tried commit 6d9158128ea517f3cbdf75819e8d81e045f600e9 and newer.
>
>Yoshimi LV2 works fine in Qtractor but crashes Qtracor (and Carla) when I try to open the GUI.
>

I'm not seeing that here, however one person had a similar crash which was
resolved with the following change (then recompiling)

Load src//UI/PartUI.fl into a text editor and search for the line:

code0 {snprintf(label,12,"%d",n+1);o->label(label);}

Change the 12 to 10.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by suedwestlicht** [comment]
The bug was introduced with:
commit 6e51728662fa0897bcd347459f6db1179b59becc
Author: abrolag <willgodfrey@musically.me.uk>
Date:   Thu Mar 21 20:09:06 2019 +0000

    Sorted out potential GCC7 build warnings

**Comment by suedwestlicht** [comment]
Changing 12 to 10 in src//UI/PartUI.fl fixes it, indeed.

Thx.

**Comment by abrolag** [comment]
On Tue, 30 Apr 2019 17:59:30 +0000 (UTC)
suedwestlicht <notifications@github.com> wrote:

>2019-03-01 is ok, 2019-04-01 crashes. Investigating further.
>

OK
Pretty certain it's that line I just mentioned then.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Tue, 30 Apr 2019 11:18:18 -0700
suedwestlicht <notifications@github.com> wrote:

>Changing 12 to 10 in src//UI/PartUI.fl fixes it, indeed.
>
>Thx.
>

Thanks for reporting it. I'll correct it in the current build.
I'll also leave this up for a while in case anyone else is following it.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
