### ISSUE TITLE
Single master instance now properly accessed -> no GUI in Qtractor

### ISSUE THREAD

**Issue by suedwestlicht** [Yoshimi/yoshimi#49]
With commit 0ecbad762b99bd29494dd8dade07a73a616ac720 I can load Yoshimi LV2 in Qtractor but the GUI doesn't open. No crash, it just doesn't open.

**Comment by suedwestlicht** [comment]
With the commit before everything is ok.

**Comment by abrolag** [comment]
That's rather odd. I'm not seeing any issues here.
How are you running it? As an LV2 plugin or standalone application?

If LV2 are you running instance per part, or single multipart instance in the 'output' section of the mixer.

Do you have the new option in  'Settings->Switches->Enable Single Master' checked? If so, try unchecking it, saving and trying again.

If all else fails, try going into the 'globals.h' file and right near the top change 'handleSingleMaster' from 'true' to 'false' and recompile.

**Comment by suedwestlicht** [comment]
I load it into Qtractor as a LV2 plugin.

I use 3 voices at once as in the mixer screenshot.
![mixer](https://user-images.githubusercontent.com/5550538/57134600-ef66c800-6da6-11e9-8a91-8f410c311574.jpg)

"Enable Single Master" is unchecked.

Changing handleSingleMaster to false and recompiling doesn't fix the issue. Strange.

**Comment by abrolag** [comment]
Hmm.
Here's another suggestion.
In 'src/Interface/Interchange' line number 73 is just a semicolon (;) try changing that to the following, and again recompile:
    singlePath = std::string(getenv("HOME")) + "/.yoshimiSingle";

This doesn't get used by LV2, but it may still be trying to find it :(

Also can you confirm that starting Yoshimi stand-alone is OK?

**Comment by suedwestlicht** [comment]
Makes no difference, both with  handleSingleMaster as false and true.

Maybe another hint: When loading the LV2 plugin into Carla it fails with:

![carla](https://user-images.githubusercontent.com/5550538/57136348-d82ad900-6dac-11e9-9c82-13fb5935d2c3.png)

**Comment by suedwestlicht** [comment]
Yoshimi standalone is ok. And the previous LV2 version that works ok in Qtractor works in Carla as well, without the undefined symbols message.

**Comment by abrolag** [comment]
Ah! I think I've got it.
The primary definition for this is in 'Main' - which LV2 never sees.
This is at line 67
It is then an 'extern' definition in 'InterChange' at line 52

Try swapping them over so the primary def is in 'InterChange'.

**Comment by suedwestlicht** [comment]
Yep. Works.

**Comment by abrolag** [comment]
On Fri, 03 May 2019 05:23:37 -0700
suedwestlicht <notifications@github.com> wrote:

>Yoshimi standalone is ok. And the previous LV2 version that works ok in Qtractor works in Carla as well, without the undefined symbols message.
>
Thanks for the extra info - hopefully I've found it this time.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by suedwestlicht** [comment]
You have :)

**Comment by abrolag** [comment]
On Fri, 03 May 2019 05:39:59 -0700
suedwestlicht <notifications@github.com> wrote:

>Yep. Works.
>
{Phew}

As a matter of interest there will be a new release 1.5.11 in the next week or
so. This feature will be disabled for that, as we're still sorting out these
corner cases, but will be back in 'master' afterwards, and hopefully will be
part of a quite major release in September.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
