### ISSUE TITLE
LV2-plugin does not show the instrument bank management buttons

### ISSUE THREAD

**Issue by ITicDigger** [Yoshimi/yoshimi#54]
If I install yoshimi compiled from source via checkinstall or via deb-file compiled via checkinstall, I get the following problem:
If you click on the name of the tool in the main window of the plug-in, the window for selecting tools from the current bank opens. For some reason, the SAVE, DELETE SWAP RENAME, and so on disappeared in this window. Similar buttons disappeared from the bank management window. It is strange that in the standalone-version these buttons are in place.

Build from sources in the standard way on Kubuntu 18.04.2 64-bit and tested on it and on Ubuntu Studio 18.04.2 64-bit - the result is the same.

This issue was first noticed by me in 1.5.11.3, but I did not have time to report this because 1.5.11.4 was howling too quickly :) and this is also observed in it.

I understand that this is most likely a checkinstall problem, but just in case I decided to report it.

**Comment by abrolag** [comment]
On Fri, 21 Jun 2019 05:44:13 -0700
ITicDigger <notifications@github.com> wrote:

>If you click on the name of the tool in the main window of the plug-in, the window for selecting tools from the current bank opens. For some reason, the SAVE, DELETE SWAP RENAME, and so on disappeared in this window. Similar buttons disappeared from the bank management window. It is strange that in the standalone-version these buttons are in place.
>
>Build from sources in the standard way on Kubuntu 18.04.2 64-bit and tested on it and on Ubuntu Studio 18.04.2 64-bit - the result is the same.
>
>The bug was first noticed by me in 1.5.11.3, but I did not have time to report this because 1.5.11.4 was howling too quickly :) and this bug is also observed in it.
>

How many instances are you running and in which host?

This is not a bug, but a deliberate decision to prevent inconstant bank
structures. The Master instance should still have all those controls (It does
here on both qtractor and Ardour) secondary ones are effectively read only. The
original problem was that people were changing the actual stored files in banks
and instruments in several different instances which left others with missing
or invalid entries.

It is a temporary feature until the devs can find a way to keep all instances
fully synchronised without a performance hit.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by ITicDigger** [comment]
> How many instances are you running and in which host?

3 instance in Ardour 5.12

For sure. Rechecked, everything as you said - the very first instance has these buttons.
