### ISSUE TITLE
1.5.11.4 is confusing

### ISSUE THREAD

**Issue by magnetophon** [Yoshimi/yoshimi#55]
This tag seems to be the same as 1.5.11.3, except it's not available on sourceforge.

**Comment by abrolag** [comment]
We had a screw up in the repository (my fault) around that time and 1.5.11.4 actually has some features that were not fully tested :( Also, somehow the update for sourceforge got missed - I don't really know a clean way out of this situation, and was rather hoping nobody would notice before we release V 1.6.0 (a poorly guarded secret)

**Comment by magnetophon** [comment]
OK, I'll pretend not to have noticed then!  :)

**Comment by abrolag** [comment]
and the good news is we appear to be on-track for release on the September 1, when Yoshimi will be 10 years old :)
