### ISSUE TITLE
tempo sync

### ISSUE THREAD

**Issue by bartart3d** [Yoshimi/yoshimi#57]
Hi all, 

this is a request to add tempo synchronisation with other applications.

I really love the sounds of zynaddsubfx and yoshimi.. one thing keeps coming up as a showstopper.. tempo sync with other applications like Ardour, or any DAW  is absent.

I recently turned to 'Surge' because I really needed a tempo synchronisation, for example for delay effects. Tempo sync really is something important. I cannot believe this has not been requested yet.

Now it has been :-)

grtz,
Bart

**Comment by abrolag** [comment]
We are actually right in the middle of preparations for the next release, but after that I'll discuss it with the other devs. I seem to recall it was mentioned before, but is actually an incredibly complex and invasive feature to add.

**Comment by abrolag** [comment]
This is now under consideration, but if successful is nevertheless likely to be a long haul. It needs some very deep changes in the code.

**Comment by abrolag** [comment]
Progress!
This is in place for testing in the current master. Currently enabled for AddSynth and PadSynth LFOs

**Comment by abrolag** [comment]
.. and we now have this for Effects where it is relevant - such as Ecol delay time.

**Comment by kramlie** [comment]
We could consider closing this now. I think all effects where it makes sense have tempo sync now. Or are there any left?

**Comment by abrolag** [comment]
On Sun, 15 Aug 2021 08:08:34 -0700
kramlie ***@***.***> wrote:

>We could consider closing this now. I think all effects where it makes sense have tempo sync now. Or are there any left?
>
I think everything's covered, but I was going to leave this visible until
after V2.1.0 is out (only a few details to clear up now). 

-- 
Will J Godfrey
https://willgodfrey.bandcamp.com/
http://yoshimi.github.io
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by bartart3d** [comment]
Great news to see this is happening :-D
I can't wait to try it out! When a build is out, I sure want to give it a spin!
