### ISSUE TITLE
I would like to be able to load and save Yoshimi projects (all 4 files) in one go.

### ISSUE THREAD

**Issue by defcronyke** [Yoshimi/yoshimi#6]
I have made a pull request #5 which implements this feature. Please let me know what you think of it. I would love to have this feature in Yoshimi regardless of how it's implemented.

**Comment by abrolag** [comment]
Hi and welcome.

I'm always interested in code contributions, but I don't understand what situation this is intended to address.

An xmz (Patch Set) file will include all currently installed xiz (Instrument) on all parts. It also stores overall volume, key shift etc.

A state file will include the current Patch Set and the current xsz (Scale) settings, along with all system settings, so it would seem to me that the state file effectively *is* a project file. The only thing it doesn't include is the new xvy (Vector Control) file, but currently that can only be managed via the command line or NRPNs.

I'm quite deeply involved in some low-level work on Yoshimi at the moment, but I'll pull your implementation into a side branch and have a look at it as soon as I have the time.

**Comment by defcronyke** [comment]
I might be wrong, but it seems like I have to load at least 2 of the files (.xmz and .state) to restore all yoshimi params. Regardless, this feature would enable quick saving and loading of the 4 save files. 

But if it's not needed that's okay. Ideally there would be one project file and we could just save and load the one file instead.

**Comment by abrolag** [comment]
Sorry to be slow coming back to this - been a bit busy!

One thing that occurs to me is that some sequencers do things in the wrong order. They load a state file *then* set control defaults. It should of course be the other way round, so I wonder if that is what you are finding. I did a re-check and can say that a state reload will definitely set absolutely everything as it was when the file was saved.  Do bear in mind that if you play a track through, it may have changed various settings from what you first set up, so if you make a state save at that point you'll have saved the wrong values - easily done :)

I've had a look through you patch. It does work but I'm afraid I really don't see any benefit from it - especially as it adds two more dependencies.

I was puzzled by the references to Windows in the code. Yoshimi is Linux only, and likely to remain that way unless a really good developer comes along!

As a general rule please try to make sure your code matches the style of the rest of a project - although I know fluid tends to make a mess of it.

Finally, although my comments seem rather negative, I do appreciate you taking the time to make a suggestion and putting together the code to implement it.
