### ISSUE TITLE
mxml: XML does not start with '<' 

### ISSUE THREAD

**Issue by svictor9** [Yoshimi/yoshimi#60]
On Arch Linux with Yoshimi 1.6.0, the recent update of mxml to version 3.1 breaks Yoshimi’s handling of xml.

First symptom: Yoshimi won’t start:
```
$ yoshimi
Yoshimi 1.6.0 is starting
mxml: XML does not start with '<' (saw '
').
XML: File /home/tor/.config/yoshimi/yoshimi.config is not XML
XML: Not good, XMLwrapper peek on an empty parentstack
XML: Not good, XMLwrapper peek on an empty parentstack
extractConfigData, no BASE_PARAMETERS branch
Bail: Yoshimi stages a strategic retreat :-(
```
I gunziped yoshimi.config manually, and there is a blank line before `<?xml version="1.0" encoding="UTF-8"?>`. I deleted that line and yoshimi started.
But next, it complained about other files which it could not read. That included .xiy and .xiz instrument files which I tried to load: 

```
Yay! We're up and running :-)
mxml: XML does not start with '<' (saw '
').
XML: File /home/tor/.config/yoshimi/yoshimi.history is not XML
XML: Not good, XMLwrapper peek on an empty parentstack
XML: Not good, XMLwrapper peek on an empty parentstack
extractHistoryData, no HISTORY branch
mxml: XML does not start with '<' (saw '
').
XML: File /home/tor/.config/yoshimi/yoshimi.banks is not XML
XML: Not good, XMLwrapper peek on an empty parentstack
XML: Not good, XMLwrapper peek on an empty parentstack
extractConfigData, no BANKLIST branch
yoshimi> mxml: XML does not start with '<' (saw '
').
XML: File /home/tor/yoshimi/banks/Victor 1/0014-Bass 4.xiy is not XML
Part: loadXML failed to load instrument file /home/tor/yoshimi/banks/Victor 1/0014-Bass 4.xiy
Main Part 1 load FAILED Instrument 0014-Bass 4missing or corrupted
mxml: XML does not start with '<' (saw '
').
XML: File /home/tor/yoshimi/banks/Victor 1/0017-terror leadbass 5.xiz is not XML
Part: loadXML failed to load instrument file /home/tor/yoshimi/banks/Victor 1/0017-terror leadbass 5.xiz
Main Part 1 load FAILED Instrument 0017-terror leadbass 5missing or corrupted
```
All these files have a line break before the first tag.
If I change some settings and save, the newly generated config file has again a blank line before the first tag. So the problem seems to be in how Yoshimi writes its xml.

According to the [mxml news](https://github.com/michaelrsweet/mxml/blob/master/CHANGES.md), mxml became more strict in the last version:
"The mxmlLoad* functions now print an error when the XML does not start with < and no parent node is supplied (Issue #256, Issue #259)"

mxml version 3.1 was released only 10 days ago. Arch incorporated it shortly after. If I downgrade mxml to version 3.0 the problem is gone and yoshimi reads its xml files just fine. 

I hope this helps. Thanks for the ongoing work on this wonderful synth!

**Comment by abrolag** [comment]
Thanks a lot for this. I was just starting to investigate as an Arch user had complained, and you've massively shortened my panic time!

**Comment by abrolag** [comment]
Well, we have a fix now, we remove any leading blank lines on loading. It's rather puzzling though. As far as I can tell, it's mxml that creates them when saving!

I'll leave this open for a few days, in case anyone else gets caught.

**Comment by svictor9** [comment]
I confirm that the problem is gone in 1.6.0.1. Thanks!
