### ISSUE TITLE
Browser version license / source code?

### ISSUE THREAD

**Issue by Catsvilles** [Yoshimi/yoshimi#67]
Hi, I'm working with the Web Audio API and I fell in love with Yoshimi and would love to play around with it and maybe use in my sound designing projects. Could you please give me more details about the license on it and if the source code is available? Cannot find much info about it. Thank you! :)

**Comment by abrolag** [comment]
On Sat, 28 Sep 2019 08:16:12 -0700
Catsvilles <notifications@github.com> wrote:

>Hi, I'm working with the Web Audio API and I fell in love with Yoshimi and would love to play around with it and maybe use in my sound designing projects. Could you please give me more details about the license on it and if the source code is available? Cannot find much info about it. Thank you! :)
>

Hi,
Yoshimi desktop itself, a Linux project, is licensed as GPL V2 or later.
And the source code is available from either:
https://github.com/Yoshimi/yoshimi

or:
https://sourceforge.net/projects/yoshimi

I've also passed this message on to the guy who ported it to the webaudio api.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by jariseon** [comment]
hi @Catsvilles, yoshimi web port is a web audio module (WAM), which in turn is MIT licensed. i'll push a fork in my repo after cleaning up a bit.

**Comment by Catsvilles** [comment]
@abrolag @jariseon Thank you very much for your time, guys! I'll wait for a fork, thanks a lot again! :)

**Comment by jariseon** [comment]
pushed yoshimi web port [here](https://github.com/jariseon/yoshimi). please raise any web version related issues in that repo :)
