### ISSUE TITLE
Virtual Keyboard: Key Mapping

### ISSUE THREAD

**Issue by exap** [Yoshimi/yoshimi#7]
At the moment the key mapping (which note plays on which key) depends on the keyboard layout. You should rather use the raw keyboard signal.

**Comment by abrolag** [comment]
I'm currently getting the next release together so that's rather a priority at the moment :)
I can see your point and it may be a workable idea. Once the dust has settled I'll ask on the list what users think. It's been this way for a very long time!

**Comment by abrolag** [comment]
We've had another look at this (sorry about the delay) but have decided to leave it more-or-less as it is. New users will always need to see the layout, so to use the raw keyboard data would actually increase the amount of work we need to do.

We currently recognise 4 common layouts (in 'Settings') and for version 1.5.0  there is a semi-graphical tooltip of the commonest layout. Over time we will add ones for the others we recognise.

Anyone can submit a new layout for the keyboard they use.

**Comment by exap** [comment]
Fair enough. Keep up the awesome work :)

**Comment by abrolag** [comment]
Thanks for the support :)
Closing this one now.
