### ISSUE TITLE
Loading a different scale shows the values for the previous one.

### ISSUE THREAD

**Issue by tigran123** [Yoshimi/yoshimi#71]
Upon startup Yoshimi uses 12tET scale, but if I load another scale (which was previously saved and I had to use the same name "12tET" because of the bug #70 )  it shows the correct values in the Tunnings section (via Scale/Show Setting) but seems to play according to the original 12tET tuning at least my ear couldn't detect any difference and the values I entered were:

```
17/16
9/8
19/16
5/4
21/16
11/8
23/16
3/2
13/8
7/4
15/8
2/1
```

(and I played "Чижик-пыжик" so the melody never left the range C4-B4).

Now, if I re-load the original 12tET (which I saved in one of the previous sessions) then it still shows the Tunings values for the previous (i.e. modified) scale. Maybe this bug is related to #70 i.e. the scales are somehow identified by the user-visible name "12tET" and the clash of names causes the confusion?

**Comment by abrolag** [comment]
Also closing this one - as noted elsewhere the original fault is fixed.
