### ISSUE TITLE
Changed scale tunings are not saved to xsz file

### ISSUE THREAD

**Issue by tigran123** [Yoshimi/yoshimi#72]
Even after downgrading to 1.5.6 (in 1.6.0 the situation is much worse) I find that if I modify the scale (and give it a new name) and save it to the file and then exit Yoshimi and re-start it and re-load the file, the tunings values shown are the same as for 12tET. And indeed, examining the actual .xsz file reveals no tuning values there --- only the name of my temperament and description. This is probably because I had to disable "Enable microtonal" value, but I had no choice but to do this, because otherwise no notes lower than A4 would sound at all. (the manual does mention that unless one ticks "Enable microtonal" the 12tET will be used, but I ignored this, because obviously it can't possibly be true).

So, how does one enter a custom scale/temperament in Yoshimi and get it saved to the file?

**Comment by tigran123** [comment]
Amazing, I have now re-saved it with "Enable Microtonal" on and then exited and re-loaded the scale and now it works, i.e. the notes lower than A4 do sound as well. Strange... I'll retry it again and if it works again I'll close this issue of course. Maybe this was "user error" :)

**Comment by abrolag** [comment]
On Fri, 18 Oct 2019 08:52:34 -0700
Tigran Aivazian <notifications@github.com> wrote:

>Even after downgrading to 1.5.6 (in 1.6.0 the situation is much worse) I find that if I modify the scale (and give it a new name) and save it to the file and then exit Yoshimi and re-start it and re-load the file, the tunings values shown are the same as for 12tET. And indeed, examining the actual .xsz file reveals no tuning values there --- only the name of my temperament and description. This is probably because I had to disable "Enable microtonal" value, but I had no choice but to do this, because otherwise no notes lower than A4 would sound at all. (the manual does mention that unless one ticks "Enable microtonal" the 12tET will be used, but I ignored this, because obviously it can't possibly be true).
>
>So, how does one enter a custom scale/temperament in Yoshimi and get it saved to the file?
>

OK, confirmed here, and a fix in progress - greatly helped by your core dump!

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
On Fri, 18 Oct 2019 08:55:20 -0700
Tigran Aivazian <notifications@github.com> wrote:

>Amazing, I have now re-saved it with "Enable Microtonal" on and then exited and re-loaded the scale and now it works, i.e. the notes lower than A4 do sound as well. Strange... I'll retry it again and if it works again I'll close this issue of course. Maybe this was "user error" :)
>
Are you building, or using snapshots?
If building we should have a bugfix up very soon.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
Closing this one as it's confusing the main issue
