### ISSUE TITLE
Suggestion: relax the limitation on 'A' note to be between 329 and 660 Hz

### ISSUE THREAD

**Issue by tigran123** [Yoshimi/yoshimi#74]
I have watched the Youtube video where the author mentions the above limitation and the reasons for it (that setting a frequency too low can damage some instruments). However, please note that tuning can sometimes be done from 'C', i.e. midi note 60 (middle 'C') and for middle 'C' a "good old" English value is 256Hz (see, e.g. Sir James Jeans' "Science and Music", 1937). So, limiting it by 329Hz makes it inconvenient (ok, one can calculate the corresponding 'A' and set it there) to tune in such scenarios. Because there is a workaround, this is not a critical issue, but a merely cosmetic one.

Also,  Pianoteq doesn't even call it "A note frequency" but just calls it "Diapason" and allows you to drag a pointer to any note, i.e. to start tuning from any note. For experimenting with temperaments Yoshimi is much more convenient than Pianoteq, but I think Yoshimi could have a similar circular representation of temperament and, more importantly, when you play a note it could show the harmonics by highlighting some points on the radii of the circle, corresponding to those harmonics, like Pianoteq does. I think it would be a nice feature to have.

**Comment by abrolag** [comment]
On Fri, 01 Nov 2019 15:29:08 -0700
Tigran Aivazian <notifications@github.com> wrote:

>I have watched the Youtube video where the author mentions the above limitation and the reasons for it (that setting a frequency too low can damage some instruments). However, please note that tuning can sometimes be done from 'C', i.e. midi note 60 (middle 'C') and for middle 'C' a "good old" English value is 256Hz (see, e.g. Sir James Jeans' "Science and Music", 1937). So, limiting it by 329Hz makes it inconvenient (ok, one can calculate the corresponding 'A' and set it there) to tune in such scenarios. Because there is a workaround, this is not a critical issue, but a merely cosmetic one.
>
>Also,  Pianoteq doesn't even call it "A note frequency" but just calls it "Diapason" and allows you to drag a pointer to any note, i.e. to start tuning from any note. For experimenting with temperaments Yoshimi is much more convenient than Pianoteq, but I think Yoshimi could have a similar circular representation of temperament and, more importantly, when you play a note it could show the harmonics by highlighting some points on the radii of the circle, corresponding to those harmonics, like Pianoteq does. I think it would be a nice feature to have.
>

Well that certainly opened a can of worms!

This:
* Pianoteq doesn't even call it "A note frequency" but just calls it Diapason" *
Gave me a clue, and some extreme search, and a revision of the Scala
documentation confirmed that we were doing it wrong, and always had been using
the wrong terminology.

It is in fact a *reference* note, which can in theory be any of the MIDI note
numbers. In the latest build that has been changed and correctly identified. We
now allow note numbers from 24 to 84 (C1 - C6) and frequencies from 30 Hz to 1.1
kHz.

Later I want to look at the possibility of maintaining at least that range, but
with some form of band limiting, so we get the out of range protection.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by tigran123** [comment]
Thank you, yes, I confirm that the change has been made and the wider range of frequencies is now accepted. Only the messages on the console still look like:

```
Scales 'A' Note Value 60
Scales 'A' Frequency Value 256.000000
```

It would be nice if it calculated from the midi value 60 the note name 'C4' and displayed that instead of 'A'.

**Comment by abrolag** [comment]
On Sat, 02 Nov 2019 08:36:17 -0700
Tigran Aivazian <notifications@github.com> wrote:

>Thank you, yes, I confirm that the change has been made and the wider range of frequencies is now accepted. Only the messages on the console still look like:
>
>```
>Scales 'A' Note Value 60
>Scales 'A' Frequency Value 256.000000
>```
>
>It would be nice if it calculated from the midi value 60 the note name 'C4' and displayed that instead of 'A'.
>

Ah! Missed that. To be consistent I'll make it things like:
Ref. note 69 (A4)
Ref. note 60 (C4)

Might take a day or two.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
Completed a while ago now so I'll close it

**Comment by tigran123** [comment]
Thank you.
