### ISSUE TITLE
Can work with Ardour?

### ISSUE THREAD

**Issue by Npizza** [Yoshimi/yoshimi#77]
Hi, I would like to connect yoshimi with Ardour DAW. Is that possible?

**Comment by abrolag** [comment]
On Mon, 30 Dec 2019 08:16:03 -0800
Npizza <notifications@github.com> wrote:

>Hi, I would like to connect yoshimi with Ardour DAW. Is that possible?
>
Yes. It can work both as an LV2 plugin, or as and external audio source.

I regularly test it as a plugin with Ardour, Qtractor and Carla.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by Npizza** [comment]
Thank you I was able to install it succesfully with Ardour in linux mint!
