### ISSUE TITLE
Segmentation fault on changing LFO Waveform

### ISSUE THREAD

**Issue by strongheart1** [Yoshimi/yoshimi#81]
Whenever I try to change the waveform of **any** LFO from the default waveform SINE to another waveforn (e.g. TRI or SQR ) i get a Segmentation fault. All other functions in the software seem to work fine.
Operating System: Linux Mint 18.3
Kernel: Linux 4.15.0-76-generic
Compiler: gcc 5.5.0

I tried with Yoshimi versions 1.7.0  and 1.6.1, both show the same error.
Is it supposed to work with this Linux  and/or compiler version at all?
 
a debug session looks like this:
 /yoshimi-git/yoshimi/src/Debug $ gdb ./yoshimi
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./yoshimi...done.
(gdb) r -a -A
Starting program: /home/user/yoshimi-git/yoshimi/src/Debug/yoshimi -a -A
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Not there
Yoshimi 1.7.0 M is starting
Basic configuration /home/user/.config/yoshimi/yoshimi.config not found, will use default settings
/home/user/.local/yoshimi/presets
/home/user/yoshimi-git/yoshimi/presets
/usr/share/yoshimi/presets
Configuration /home/user/.config/yoshimi/yoshimi-0.instance not found, will use default settings
[New Thread 0x7fffeb873700 (LWP 7066)]
Error, alsa audio: alsa audio mmap not possible: Invalid argument
March is Little Endian
Card Format is Signed Little Endian 32 Bit 2 Channel
Using alsa_audio for audio and alsa_midi for midi
[New Thread 0x7fffeb072700 (LWP 7067)]
Alsa audio priority is 40
[New Thread 0x7fffea871700 (LWP 7068)]
Alsa midi priority is 39
[New Thread 0x7fffea070700 (LWP 7069)]
Yoshimi 1.7.0 M
Build Number 1749
Clientname: yoshimi
Audio: alsa -> 'default'
Midi: alsa -> 'Scarlett 2i4 USB:0'
Oscilsize: 512
Samplerate: 48000
Period size: 256

Yay! We're up and running :-)
[New Thread 0x7fffe986f700 (LWP 7070)]
Missing history file

Found 704 instruments in 24 banks
No bank 0 in root 0. Current bank is 5
[New Thread 0x7fffe8e16700 (LWP 7071)]
yoshimi> Part 1 Kit 1 AddSynth Filter An Type l1
Part 1 Kit 1 AddSynth Filter An Type l2

Thread 3 "yoshimi" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb072700 (LWP 7067)]
__memcmp_sse2 () at ../sysdeps/x86_64/multiarch/../memcmp.S:56
56	../sysdeps/x86_64/multiarch/../memcmp.S: No such file or directory.
(gdb) backtrace
#0  __memcmp_sse2 () at ../sysdeps/x86_64/multiarch/../memcmp.S:56
#1  0x00007ffff5f1553a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000004a4bd1 in std::operator==<char, std::char_traits<char>, std::allocator<char> > (__lhs=<error: Cannot access memory at address 0x1>, __rhs=0x6ff693 "SIne")
    at /usr/include/c++/5/bits/basic_string.h:5034
#3  0x00000000004a4ab8 in std::operator!=<char, std::char_traits<char>, std::allocator<char> > (__lhs=<error: Cannot access memory at address 0x1>, __rhs=0x6ff693 "SIne")
    at /usr/include/c++/5/bits/basic_string.h:5072
#4  0x00000000004b0985 in DataText::resolveLFO[abi:cxx11](CommandBlock*, bool) (
    this=0xaabd60, getData=0x7fffeb071bd0, addValue=true)
    at /home/user/yoshimi-git/yoshimi/src/Interface/Data2Text.cpp:2646
#5  0x00000000004a6dfb in DataText::resolveAll[abi:cxx11](SynthEngine*, CommandBlock*, bool)
    (this=0xaabd60, _synth=0xaabca0, getData=0x7fffeb071bd0, addValue=true)
    at /home/user/yoshimi-git/yoshimi/src/Interface/Data2Text.cpp:271
#6  0x00000000004953cd in InterChange::resolveReplies (this=0xaabd60, 
    getData=0x7fffeb071bd0)
    at /home/user/yoshimi-git/yoshimi/src/Interface/InterChange.cpp:1462
#7  0x000000000048ecbd in InterChange::sortResultsThread (this=0xaabd60)
    at /home/user/yoshimi-git/yoshimi/src/Interface/InterChange.cpp:234
#8  0x000000000048ea62 in InterChange::_sortResultsThread (arg=0xaabd60)
    at /home/user/yoshimi-git/yoshimi/src/Interface/InterChange.cpp:171
#9  0x00007ffff747d6ba in start_thread (arg=0x7fffeb072700) at pthread_create.c:333
---Type <return> to continue, or q <return> to quit---
#10 0x00007ffff561141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) frame 1
#1  0x00007ffff5f1553a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) frame 4
#4  0x00000000004b0985 in DataText::resolveLFO[abi:cxx11](CommandBlock*, bool) (
    this=0xaabd60, getData=0x7fffeb071bd0, addValue=true)
    at /home/user/yoshimi-git/yoshimi/src/Interface/Data2Text.cpp:2646
2646	                while (LFOlist [idx] != "SIne")
(gdb)_

**Comment by abrolag** [comment]
On Fri, 31 Jan 2020 09:16:49 -0800
strongheart1 <notifications@github.com> wrote:

>Whenever I try to change the waveform of **any** LFO from the default waveform SINE to another waveforn (e.g. TRI or SQR ) i get a Segmentation fault. All other functions in the software seem to work fine.
>Operating System: Linux Mint 18.3
>Kernel: Linux 4.15.0-76-generic
>Compiler: gcc 5.5.0
>
>I tried with Yoshimi versions 1.7.0  and 1.6.1, both show the same error.
>Is it supposed to work with this Linux  and/or compiler version at all?

Confirmed here.
That's a bad, getting on it right away :(

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by abrolag** [comment]
OK, found out *exactly* where it is... now to find out why :?

**Comment by abrolag** [comment]
Fixed now in the current master and in bugfix version 1.7.0.1

I'll leave this up for a while in case other people hit it.

**Comment by strongheart1** [comment]
It works for me now, too. Thanks a lot!
