### ISSUE TITLE
Random patch changes.

### ISSUE THREAD

**Issue by magnetophon** [Yoshimi/yoshimi#89]
I have an ardour song with a couple of Yoshimis in it.
Sometimes they randomly change patch, playing a different sound.

I can attach the ardour project if wanted.

This is with version 1.7.0.1.

**Comment by abrolag** [comment]
On Thu, 02 Apr 2020 02:51:25 -0700
Bart Brouns <notifications@github.com> wrote:

>I have an ardour song with a couple of Yoshimis in it.
>Sometimes they randomly change patch, playing a different sound.
>
>I can attach the ardour project if wanted.
>
>This is with version 1.7.0.1. 
>
Before doing that, are you actually intending to make any patch changes via
MIDI?

Do you have the 'Reports' window open? That will show you if Ardour is sending
program changes that you're not expecting.

If so, you try going to Yoshimi->Settings->MIDI and disable 'Enable Program
Change' and let us know if that solves the problem.

You could also try enabling 'Log Incoming Events" and to see if spurious
controller messages are being sent.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by magnetophon** [comment]
I'm not intending to send patch changes.
I opened the reports window after a change, but there was nothing there.
I also enabled logging. Where can I find the log?

**Comment by abrolag** [comment]
Hmmm.
In  'Settings->Main settings' you should have 'Send reports to:' set to 'Console
Window'. is that what you've got?

All logging then goes there, otherwise it gets sent to stdio

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by magnetophon** [comment]
Now I do, thanks.

**Comment by magnetophon** [comment]
I got a log:
```
Config Reports to console window
Config saved /home/bart/.config/yoshimi/yoshimi-5.instance
Unsupported event: 0x4f
Unsupported event: 0x4b
Main Part 4 load FAILED No instrument at 51 in this bank
Unsupported event: 0x0f
Unsupported event: 0x57
Unsupported event: 0x84
Unsupported event: 0x4f
Unsupported event: 0x02
Unsupported event: 0x7e
Unsupported event: 0x53
Unsupported event: 0x28
Main Part 16 load FAILED No instrument at 240 in this bank
Unsupported event: 0x4f
Chan 4   CC Ch Press   Value 196
Unsupported event: 0x79
Unsupported event: 0x90
Unsupported event: 0x3b
Unsupported event: 0x47
Unsupported event: 0x98
Unsupported event: 0xf0
Unsupported event: 0x63
Unsupported event: 0x71
Unsupported event: 0x89
Unsupported event: 0x3c
Unsupported event: 0x3c
Unsupported event: 0x61
Main Part 3 load FAILED No instrument at 102 in this bank
Unsupported event: 0xfe
Chan 4   CC Pitchwheel   Value 2230
Unsupported event: 0x47
Unsupported event: 0x9b
Chan 6   CC 128   Value 182
Main Part 6 load FAILED No instrument at 151 in this bank
Unsupported event: 0x22
Unsupported event: 0x7a
Unsupported event: 0x29
Unsupported event: 0x71
Unsupported event: 0x58
Unsupported event: 0x71
Unsupported event: 0x4f
Unsupported event: 0x16
Unsupported event: 0x6b
Unsupported event: 0x3d
Unsupported event: 0x40
Chan 1   CC 64   Value 0
Chan 2   CC 64   Value 0
Chan 3   CC 64   Value 0
Chan 4   CC 64   Value 0
Chan 5   CC 64   Value 0
Chan 6   CC 64   Value 0
Chan 7   CC 64   Value 0
Chan 8   CC 64   Value 0
Chan 9   CC 64   Value 0
Chan 10   CC 64   Value 0
Chan 11   CC 64   Value 0
Chan 12   CC 64   Value 0
Chan 13   CC 64   Value 0
Chan 14   CC 64   Value 0
Chan 15   CC 64   Value 0
Chan 16   CC 64   Value 0
Unsupported event: 0x29
Unsupported event: 0x71
Unsupported event: 0x4f
Unsupported event: 0x4f
Unsupported event: 0x5d
Main Part 13 load FAILED No instrument at 47 in this bank
Chan 3   CC Ch Press   Value 232
Unsupported event: 0x5d
Unsupported event: 0x71
Chan 2   CC Pitchwheel   Value 8102
Unsupported event: 0x40
Unsupported event: 0x16
Unsupported event: 0x6b
Unsupported event: 0x90
Unsupported event: 0x97
Chan 13   CC 79   Value 123
Main Part 1 loaded 0042-Soft Arpeggio4
```

Does that indicate Ardour is sending the changes?

**Comment by abrolag** [comment]
Yes. It's also sending a lot of other messages that Yoshimi doesn't support. You will notice that Yoshimi reports but completely ignores these, and the same with invalid program changes. There one valid one at the end it seems to have hit by chance, and it also seems at some point the first bank of instruments (arpeggios) has been set.
I'm wondering where that MIDI file originally came from. There are some CCs that don't have a standard designation at all.

**Comment by abrolag** [comment]
No further info so closing this.

**Comment by magnetophon** [comment]
Sorry for not reporting back!
Which info would you like to have?

**Comment by abrolag** [comment]
On Thu, 07 May 2020 05:57:28 -0700
Bart Brouns <notifications@github.com> wrote:

>Sorry for not reporting back!
>Which info would you like to have?
>
Did you resolve the issue?
Did you find out where those spurious CCs came from?

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by magnetophon** [comment]
No, I don't know how to troubleshoot this.

**Comment by abrolag** [comment]
In Settings->MIDI set 'Bank Root Change' and 'Bank Change'  to Off
Also uncheck 'Enable Program Change'
Does it then behave as you would expect?

**Comment by magnetophon** [comment]
Yes it does.

**Comment by abrolag** [comment]
OK, so that gets you out of trouble and underlines the fact it's not a Yoshimi issue, and I very much doubt it's an Ardour one, which leaves just the source of the original MIDI file, which I'm guessing was developed on and/or for a totally different synth setup.

I'll leave this up for a while again in case anyone is watching it, then close.
