### ISSUE TITLE
Feature request: confirm overwrite when changing patch from midi

### ISSUE THREAD

**Issue by magnetophon** [Yoshimi/yoshimi#91]
When yoshimi gets a midi patch change, and the current sound has not been saved, a popup should appear asking if I'm sure I want to lose the current settings.

**Comment by abrolag** [comment]
No. This would break the smooth operation of normal MIDI messages in a non-standard manner. If patch changes are a problem simply disable them in settings.

**Comment by magnetophon** [comment]
OK, fair enough.
