### ISSUE TITLE
yoshimi doesn't adhere to XDG Base Directory Specifications

### ISSUE THREAD

**Issue by dvzrv** [Yoshimi/yoshimi#98]
Hi!

Yoshimi doesn't adhere to the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

* Presets: `~/.local/yoshimi/` -> `$XDG_DATA_HOME/yoshimi/` (e.g. `~/.local/share/yoshimi/`)
* History (essentially a log file?): `~/.yoshimi_history` -> `$XDG_RUNTIME_DIR/yoshimi.log` (e.g. `/run/user/<uid>/yoshimi.log`) or `$XDG_CACHE_HOME/yoshimi.log` (e.g. `~/.cache/yoshimi.log`)

**Comment by abrolag** [comment]
On Sat, 18 Apr 2020 09:11:20 -0700
David Runge <notifications@github.com> wrote:

>Hi!
>
>Yoshimi doesn't adhere to the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
>
>* Presets: `~/.local/yoshimi/` -> `$XDG_DATA_HOME/yoshimi/` (e.g. `~/.local/share/yoshimi/`)
>* History (essentially a log file?): `~/.yoshimi_history` -> `$XDG_RUNTIME_DIR/yoshimi.log` (e.g. `/run/user/<uid>/yoshimi.log`) or `$XDG_CACHE_HOME/yoshimi.log` (e.g. `~/.cache/yoshimi.log`)
>
Hi David,

Thanks for the information.
In the latest builds Presets has already been moved to ~/.local/share/yoshimi/

I'll take a look at moving history later, although I'm not entirely sure it's
a log file, and we already have a runtime log potentially going to stdout.

We are right on the verge of a new release, and concentrating on bugs right now
(one turned up this morning) :(

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by dvzrv** [comment]
cool, thanks for looking into it! :-)

**Comment by abrolag** [comment]
I've come to the conclusion that the history file is definitely not a log (although possibly badly named). It stores only the last 20 or so of each type of file seen. It then reorganises this if any are selected, so never grows beyond that number. As an example, if you select the 10th instrument in the list, that immediately becomes the first, and original entries 1 to 9 shuffle up, so the order of the entries it can't be regarded as a linear record of past events.

Having said that, by the same token it's not a config file either, so I'll think out how (and where) to move it.

**Comment by abrolag** [comment]
This is now done. It is now " in '/HOME/{user}/.local/yoshimi' and is named 'recent'.
The change is transparent and for existing users will look there first, and if it's not there, fetch the old one instead.

I'll leave this open for a while in case anyone else is watching.
