### ISSUE TITLE
yoshimi virtual keyboard key can get stuck

### ISSUE THREAD

**Issue by shimpe** [Yoshimi/yoshimi#99]
Recipe to reproduce:

1. show virtual keyboard
2. press computer keyboard key (a letter) to activate a note
3. with the letter key still pressed, change one of the knobs/sliders using the mouse
4. release the letter key: now the virtual piano keyboard key is stuck
5. it can not be unstuck using the computer mouse, but it can be by giving focus to the virtual piano keyboard and pressing the same letter again

(It's a minor annoyance once you know how to get it unstuck again)

**Comment by abrolag** [comment]
On Thu, 23 Apr 2020 09:31:57 -0700
shiihs <notifications@github.com> wrote:

>Recipe to reproduce:
>
>1. show virtual keyboard
>2. press computer keyboard key (a letter) to activate a note
>3. with the letter key still pressed, change one of the knobs/sliders using the mouse
>4. release the letter key: now the virtual piano keyboard key is stuck
>5. it can not be unstuck using the computer mouse, but it can be by giving focus to the virtual piano keyboard and pressing the same letter again
>
>(It's a minor annoyance once you know how to get it unstuck again)
>
This is not a bug. The virtual keyboard can't recognise key events if it
doesn't have focus. Mouse and keyboard are linked focus-wise in FLTK.

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by kramlie** [comment]
Also, I use this "feature" a lot when I don't have a keyboard handy: Start a note, change focus, and the note will keep on playing while I tweak knobs. Going back to the keyboard and pressing the same key "turns it off" again. It's also possible to press the "Stop!" button in the main window.

**Comment by shimpe** [comment]
Ok I'll close it then.
